/*********************************************************************************************/
TITLE1 "ACS SES - Education";

* AUTHOR: Patricia Ferido;

* DATE: 8/6/2019;

* PURPOSE: Macro to read in ACS 5 year Summary Table S1501

	Input variables:
		yr - last year represented in the 5 year Summary Table;
	
* INPUT: acs_[yr]_5yr_S1501_with_ann.xlsx;

* OUTPUT: acs_s1501_[yrs]_raw, acs_s1501_;

options compress=yes nocenter ls=150 ps=200 errors=5  errorcheck=strict mprint merror
	mergenoby=warn varlenchk=error dkricond=error dkrocond=error msglevel=i;
/*********************************************************************************************/

%macro s1501_1517(yr);
data og&yr..ACS_S1501_&yr._RAW    ;
           %let _EFIERR_ = 0; /* set the ERROR detection macro variable */
           infile "&&raw&yr./ACS_&yr._5YR_S1501_with_ann.csv" delimiter = "," MISSOVER DSD lrecl=32767 firstobs=3 ;
              informat GEO_id $14. ;
              informat GEO_id2 $10. ;
              informat GEO_display_label $11. ;
              informat HC01_EST_VC02 $10. ;
              informat HC01_MOE_VC02 $5. ;
              informat HC02_EST_VC02 $3. ;
              informat HC02_MOE_VC02 $3. ;
              informat HC03_EST_VC02 $10. ;
              informat HC03_MOE_VC02 $5. ;
              informat HC04_EST_VC02 $3. ;
              informat HC04_MOE_VC02 $3. ;
              informat HC05_EST_VC02 $10. ;
              informat HC05_MOE_VC02 $5. ;
              informat HC06_EST_VC02 $3. ;
              informat HC06_MOE_VC02 $3. ;
              informat HC01_EST_VC03 $10. ;
              informat HC01_MOE_VC03 $10. ;
              informat HC02_EST_VC03 $10. ;
              informat HC02_MOE_VC03 $10. ;
              informat HC03_EST_VC03 $10. ;
              informat HC03_MOE_VC03 $10. ;
              informat HC04_EST_VC03 $10. ;
              informat HC04_MOE_VC03 $10. ;
              informat HC05_EST_VC03 $10. ;
              informat HC05_MOE_VC03 $10. ;
              informat HC06_EST_VC03 $10. ;
              informat HC06_MOE_VC03 $10. ;
              informat HC01_EST_VC04 $10. ;
              informat HC01_MOE_VC04 $10. ;
              informat HC02_EST_VC04 $10. ;
              informat HC02_MOE_VC04 $10. ;
              informat HC03_EST_VC04 $10. ;
              informat HC03_MOE_VC04 $10. ;
              informat HC04_EST_VC04 $10. ;
              informat HC04_MOE_VC04 $10. ;
              informat HC05_EST_VC04 $10. ;
              informat HC05_MOE_VC04 $10. ;
              informat HC06_EST_VC04 $10. ;
              informat HC06_MOE_VC04 $10. ;
              informat HC01_EST_VC05 $10. ;
              informat HC01_MOE_VC05 $10. ;
              informat HC02_EST_VC05 $10. ;
              informat HC02_MOE_VC05 $10. ;
              informat HC03_EST_VC05 $10. ;
              informat HC03_MOE_VC05 $10. ;
              informat HC04_EST_VC05 $10. ;
              informat HC04_MOE_VC05 $10. ;
              informat HC05_EST_VC05 $10. ;
              informat HC05_MOE_VC05 $10. ;
              informat HC06_EST_VC05 $10. ;
              informat HC06_MOE_VC05 $10. ;
              informat HC01_EST_VC06 $10. ;
              informat HC01_MOE_VC06 $10. ;
              informat HC02_EST_VC06 $10. ;
              informat HC02_MOE_VC06 $10. ;
              informat HC03_EST_VC06 $10. ;
              informat HC03_MOE_VC06 $10. ;
              informat HC04_EST_VC06 $10. ;
              informat HC04_MOE_VC06 $10. ;
              informat HC05_EST_VC06 $10. ;
              informat HC05_MOE_VC06 $10. ;
              informat HC06_EST_VC06 $10. ;
              informat HC06_MOE_VC06 $10. ;
              informat HC01_EST_VC08 $10. ;
              informat HC01_MOE_VC08 $5. ;
              informat HC02_EST_VC08 $3. ;
              informat HC02_MOE_VC08 $3. ;
              informat HC03_EST_VC08 $10. ;
              informat HC03_MOE_VC08 $5. ;
              informat HC04_EST_VC08 $3. ;
              informat HC04_MOE_VC08 $3. ;
              informat HC05_EST_VC08 $10. ;
              informat HC05_MOE_VC08 $5. ;
              informat HC06_EST_VC08 $3. ;
              informat HC06_MOE_VC08 $3. ;
              informat HC01_EST_VC09 $10. ;
              informat HC01_MOE_VC09 $10. ;
              informat HC02_EST_VC09 $10. ;
              informat HC02_MOE_VC09 $10. ;
              informat HC03_EST_VC09 $10. ;
              informat HC03_MOE_VC09 $10. ;
              informat HC04_EST_VC09 $10. ;
              informat HC04_MOE_VC09 $10. ;
              informat HC05_EST_VC09 $10. ;
              informat HC05_MOE_VC09 $10. ;
              informat HC06_EST_VC09 $10. ;
              informat HC06_MOE_VC09 $10. ;
              informat HC01_EST_VC10 $10. ;
              informat HC01_MOE_VC10 $10. ;
              informat HC02_EST_VC10 $10. ;
              informat HC02_MOE_VC10 $10. ;
              informat HC03_EST_VC10 $10. ;
              informat HC03_MOE_VC10 $10. ;
              informat HC04_EST_VC10 $10. ;
              informat HC04_MOE_VC10 $10. ;
              informat HC05_EST_VC10 $10. ;
              informat HC05_MOE_VC10 $10. ;
              informat HC06_EST_VC10 $10. ;
              informat HC06_MOE_VC10 $10. ;
              informat HC01_EST_VC11 $10. ;
              informat HC01_MOE_VC11 $10. ;
              informat HC02_EST_VC11 $10. ;
              informat HC02_MOE_VC11 $10. ;
              informat HC03_EST_VC11 $10. ;
              informat HC03_MOE_VC11 $10. ;
              informat HC04_EST_VC11 $10. ;
              informat HC04_MOE_VC11 $10. ;
              informat HC05_EST_VC11 $10. ;
              informat HC05_MOE_VC11 $10. ;
              informat HC06_EST_VC11 $10. ;
              informat HC06_MOE_VC11 $10. ;
              informat HC01_EST_VC12 $10. ;
              informat HC01_MOE_VC12 $10. ;
              informat HC02_EST_VC12 $10. ;
              informat HC02_MOE_VC12 $10. ;
              informat HC03_EST_VC12 $10. ;
              informat HC03_MOE_VC12 $10. ;
              informat HC04_EST_VC12 $10. ;
              informat HC04_MOE_VC12 $10. ;
              informat HC05_EST_VC12 $10. ;
							informat HC05_MOE_VC12 $10. ;
              informat HC06_EST_VC12 $10. ;
              informat HC06_MOE_VC12 $10. ;
              informat HC01_EST_VC13 $10. ;
              informat HC01_MOE_VC13 $10. ;
              informat HC02_EST_VC13 $10. ;
              informat HC02_MOE_VC13 $10. ;
              informat HC03_EST_VC13 $10. ;
              informat HC03_MOE_VC13 $10. ;
              informat HC04_EST_VC13 $10. ;
              informat HC04_MOE_VC13 $10. ;
              informat HC05_EST_VC13 $10. ;
              informat HC05_MOE_VC13 $10. ;
              informat HC06_EST_VC13 $10. ;
              informat HC06_MOE_VC13 $10. ;
              informat HC01_EST_VC14 $10. ;
              informat HC01_MOE_VC14 $10. ;
              informat HC02_EST_VC14 $10. ;
              informat HC02_MOE_VC14 $10. ;
              informat HC03_EST_VC14 $10. ;
              informat HC03_MOE_VC14 $10. ;
              informat HC04_EST_VC14 $10. ;
              informat HC04_MOE_VC14 $10. ;
              informat HC05_EST_VC14 $10. ;
              informat HC05_MOE_VC14 $10. ;
              informat HC06_EST_VC14 $10. ;
              informat HC06_MOE_VC14 $10. ;
              informat HC01_EST_VC15 $10. ;
              informat HC01_MOE_VC15 $10. ;
              informat HC02_EST_VC15 $10. ;
              informat HC02_MOE_VC15 $10. ;
              informat HC03_EST_VC15 $10. ;
              informat HC03_MOE_VC15 $10. ;
              informat HC04_EST_VC15 $10. ;
              informat HC04_MOE_VC15 $10. ;
              informat HC05_EST_VC15 $10. ;
              informat HC05_MOE_VC15 $10. ;
              informat HC06_EST_VC15 $10. ;
              informat HC06_MOE_VC15 $10. ;
              informat HC01_EST_VC17 $3. ;
              informat HC01_MOE_VC17 $3. ;
              informat HC02_EST_VC17 $10. ;
              informat HC02_MOE_VC17 $10. ;
              informat HC03_EST_VC17 $3. ;
              informat HC03_MOE_VC17 $3. ;
              informat HC04_EST_VC17 $10. ;
              informat HC04_MOE_VC17 $10. ;
              informat HC05_EST_VC17 $3. ;
              informat HC05_MOE_VC17 $3. ;
              informat HC06_EST_VC17 $10. ;
              informat HC06_MOE_VC17 $10. ;
              informat HC01_EST_VC18 $3. ;
              informat HC01_MOE_VC18 $3. ;
              informat HC02_EST_VC18 $10. ;
              informat HC02_MOE_VC18 $10. ;
              informat HC03_EST_VC18 $3. ;
              informat HC03_MOE_VC18 $3. ;
              informat HC04_EST_VC18 $10. ;
              informat HC04_MOE_VC18 $10. ;
              informat HC05_EST_VC18 $3. ;
              informat HC05_MOE_VC18 $3. ;
              informat HC06_EST_VC18 $10. ;
              informat HC06_MOE_VC18 $10. ;
              informat HC01_EST_VC20 $10. ;
              informat HC01_MOE_VC20 $5. ;
              informat HC02_EST_VC20 $3. ;
              informat HC02_MOE_VC20 $3. ;
              informat HC03_EST_VC20 $10. ;
              informat HC03_MOE_VC20 $5. ;
              informat HC04_EST_VC20 $3. ;
              informat HC04_MOE_VC20 $3. ;
              informat HC05_EST_VC20 $10. ;
              informat HC05_MOE_VC20 $5. ;
              informat HC06_EST_VC20 $3. ;
              informat HC06_MOE_VC20 $3. ;
              informat HC01_EST_VC21 $10. ;
              informat HC01_MOE_VC21 $10. ;
              informat HC02_EST_VC21 $10. ;
              informat HC02_MOE_VC21 $10. ;
              informat HC03_EST_VC21 $10. ;
              informat HC03_MOE_VC21 $10. ;
              informat HC04_EST_VC21 $10. ;
              informat HC04_MOE_VC21 $10. ;
              informat HC05_EST_VC21 $10. ;
              informat HC05_MOE_VC21 $10. ;
              informat HC06_EST_VC21 $10. ;
              informat HC06_MOE_VC21 $10. ;
              informat HC01_EST_VC22 $10. ;
              informat HC01_MOE_VC22 $10. ;
              informat HC02_EST_VC22 $10. ;
              informat HC02_MOE_VC22 $10. ;
              informat HC03_EST_VC22 $10. ;
              informat HC03_MOE_VC22 $10. ;
              informat HC04_EST_VC22 $10. ;
              informat HC04_MOE_VC22 $10. ;
              informat HC05_EST_VC22 $10. ;
              informat HC05_MOE_VC22 $10. ;
              informat HC06_EST_VC22 $10. ;
              informat HC06_MOE_VC22 $10. ;
              informat HC01_EST_VC24 $10. ;
              informat HC01_MOE_VC24 $5. ;
              informat HC02_EST_VC24 $3. ;
              informat HC02_MOE_VC24 $3. ;
              informat HC03_EST_VC24 $10. ;
              informat HC03_MOE_VC24 $5. ;
              informat HC04_EST_VC24 $3. ;
              informat HC04_MOE_VC24 $3. ;
              informat HC05_EST_VC24 $10. ;
              informat HC05_MOE_VC24 $5. ;
              informat HC06_EST_VC24 $3. ;
              informat HC06_MOE_VC24 $3. ;
              informat HC01_EST_VC25 $10. ;
              informat HC01_MOE_VC25 $10. ;
              informat HC02_EST_VC25 $10. ;
              informat HC02_MOE_VC25 $10. ;
              informat HC03_EST_VC25 $10. ;
              informat HC03_MOE_VC25 $10. ;
              informat HC04_EST_VC25 $10. ;
              informat HC04_MOE_VC25 $10. ;
              informat HC05_EST_VC25 $10. ;
              informat HC05_MOE_VC25 $10. ;
              informat HC06_EST_VC25 $10. ;
              informat HC06_MOE_VC25 $10. ;
              informat HC01_EST_VC26 $10. ;
              informat HC01_MOE_VC26 $10. ;
              informat HC02_EST_VC26 $10. ;
              informat HC02_MOE_VC26 $10. ;
              informat HC03_EST_VC26 $10. ;
              informat HC03_MOE_VC26 $10. ;
              informat HC04_EST_VC26 $10. ;
              informat HC04_MOE_VC26 $10. ;
              informat HC05_EST_VC26 $10. ;
              informat HC05_MOE_VC26 $10. ;
              informat HC06_EST_VC26 $10. ;
              informat HC06_MOE_VC26 $10. ;
              informat HC01_EST_VC28 $10. ;
              informat HC01_MOE_VC28 $5. ;
              informat HC02_EST_VC28 $3. ;
              informat HC02_MOE_VC28 $3. ;
              informat HC03_EST_VC28 $10. ;
              informat HC03_MOE_VC28 $5. ;
              informat HC04_EST_VC28 $3. ;
              informat HC04_MOE_VC28 $3. ;
              informat HC05_EST_VC28 $10. ;
              informat HC05_MOE_VC28 $5. ;
              informat HC06_EST_VC28 $3. ;
              informat HC06_MOE_VC28 $3. ;
              informat HC01_EST_VC29 $10. ;
              informat HC01_MOE_VC29 $10. ;
              informat HC02_EST_VC29 $10. ;
              informat HC02_MOE_VC29 $10. ;
              informat HC03_EST_VC29 $10. ;
              informat HC03_MOE_VC29 $10. ;
              informat HC04_EST_VC29 $10. ;
              informat HC04_MOE_VC29 $10. ;
              informat HC05_EST_VC29 $10. ;
              informat HC05_MOE_VC29 $10. ;
              informat HC06_EST_VC29 $10. ;
              informat HC06_MOE_VC29 $10. ;
              informat HC01_EST_VC30 $10. ;
              informat HC01_MOE_VC30 $10. ;
              informat HC02_EST_VC30 $10. ;
              informat HC02_MOE_VC30 $10. ;
              informat HC03_EST_VC30 $10. ;
              informat HC03_MOE_VC30 $10. ;
              informat HC04_EST_VC30 $10. ;
              informat HC04_MOE_VC30 $10. ;
              informat HC05_EST_VC30 $10. ;
              informat HC05_MOE_VC30 $10. ;
              informat HC06_EST_VC30 $10. ;
              informat HC06_MOE_VC30 $10. ;
              informat HC01_EST_VC32 $10. ;
              informat HC01_MOE_VC32 $5. ;
              informat HC02_EST_VC32 $3. ;
              informat HC02_MOE_VC32 $3. ;
              informat HC03_EST_VC32 $10. ;
              informat HC03_MOE_VC32 $5. ;
              informat HC04_EST_VC32 $3. ;
              informat HC04_MOE_VC32 $3. ;
              informat HC05_EST_VC32 $10. ;
              informat HC05_MOE_VC32 $5. ;
              informat HC06_EST_VC32 $3. ;
              informat HC06_MOE_VC32 $3. ;
              informat HC01_EST_VC33 $10. ;
              informat HC01_MOE_VC33 $10. ;
              informat HC02_EST_VC33 $10. ;
              informat HC02_MOE_VC33 $10. ;
              informat HC03_EST_VC33 $10. ;
              informat HC03_MOE_VC33 $10. ;
              informat HC04_EST_VC33 $10. ;
              informat HC04_MOE_VC33 $10. ;
              informat HC05_EST_VC33 $10. ;
              informat HC05_MOE_VC33 $10. ;
              informat HC06_EST_VC33 $10. ;
              informat HC06_MOE_VC33 $10. ;
              informat HC01_EST_VC34 $10. ;
              informat HC01_MOE_VC34 $10. ;
              informat HC02_EST_VC34 $10. ;
							informat HC02_MOE_VC34 $10. ;
              informat HC03_EST_VC34 $10. ;
              informat HC03_MOE_VC34 $10. ;
              informat HC04_EST_VC34 $10. ;
              informat HC04_MOE_VC34 $10. ;
              informat HC05_EST_VC34 $10. ;
              informat HC05_MOE_VC34 $10. ;
              informat HC06_EST_VC34 $10. ;
              informat HC06_MOE_VC34 $10. ;
              informat HC01_EST_VC37 $10. ;
              informat HC01_MOE_VC37 $10. ;
              informat HC02_EST_VC37 $3. ;
              informat HC02_MOE_VC37 $3. ;
              informat HC03_EST_VC37 $10. ;
              informat HC03_MOE_VC37 $10. ;
              informat HC04_EST_VC37 $3. ;
              informat HC04_MOE_VC37 $3. ;
              informat HC05_EST_VC37 $10. ;
              informat HC05_MOE_VC37 $10. ;
              informat HC06_EST_VC37 $3. ;
              informat HC06_MOE_VC37 $3. ;
              informat HC01_EST_VC38 $10. ;
              informat HC01_MOE_VC38 $10. ;
              informat HC02_EST_VC38 $10. ;
              informat HC02_MOE_VC38 $10. ;
              informat HC03_EST_VC38 $10. ;
              informat HC03_MOE_VC38 $10. ;
              informat HC04_EST_VC38 $10. ;
              informat HC04_MOE_VC38 $10. ;
              informat HC05_EST_VC38 $10. ;
              informat HC05_MOE_VC38 $10. ;
              informat HC06_EST_VC38 $10. ;
              informat HC06_MOE_VC38 $10. ;
              informat HC01_EST_VC39 $10. ;
              informat HC01_MOE_VC39 $10. ;
              informat HC02_EST_VC39 $10. ;
              informat HC02_MOE_VC39 $10. ;
              informat HC03_EST_VC39 $10. ;
              informat HC03_MOE_VC39 $10. ;
              informat HC04_EST_VC39 $10. ;
              informat HC04_MOE_VC39 $10. ;
              informat HC05_EST_VC39 $10. ;
              informat HC05_MOE_VC39 $10. ;
              informat HC06_EST_VC39 $10. ;
              informat HC06_MOE_VC39 $10. ;
              informat HC01_EST_VC41 $10. ;
              informat HC01_MOE_VC41 $10. ;
              informat HC02_EST_VC41 $3. ;
              informat HC02_MOE_VC41 $3. ;
              informat HC03_EST_VC41 $10. ;
              informat HC03_MOE_VC41 $10. ;
              informat HC04_EST_VC41 $3. ;
              informat HC04_MOE_VC41 $3. ;
              informat HC05_EST_VC41 $10. ;
              informat HC05_MOE_VC41 $10. ;
              informat HC06_EST_VC41 $3. ;
              informat HC06_MOE_VC41 $3. ;
              informat HC01_EST_VC42 $10. ;
              informat HC01_MOE_VC42 $10. ;
              informat HC02_EST_VC42 $5. ;
              informat HC02_MOE_VC42 $4. ;
              informat HC03_EST_VC42 $10. ;
              informat HC03_MOE_VC42 $10. ;
              informat HC04_EST_VC42 $5. ;
              informat HC04_MOE_VC42 $5. ;
              informat HC05_EST_VC42 $10. ;
              informat HC05_MOE_VC42 $10. ;
              informat HC06_EST_VC42 $5. ;
              informat HC06_MOE_VC42 $4. ;
              informat HC01_EST_VC43 $10. ;
              informat HC01_MOE_VC43 $10. ;
              informat HC02_EST_VC43 $5. ;
              informat HC02_MOE_VC43 $4. ;
              informat HC03_EST_VC43 $10. ;
              informat HC03_MOE_VC43 $10. ;
              informat HC04_EST_VC43 $5. ;
              informat HC04_MOE_VC43 $5. ;
              informat HC05_EST_VC43 $10. ;
              informat HC05_MOE_VC43 $10. ;
              informat HC06_EST_VC43 $5. ;
              informat HC06_MOE_VC43 $4. ;
              informat HC01_EST_VC45 $10. ;
              informat HC01_MOE_VC45 $10. ;
              informat HC02_EST_VC45 $3. ;
              informat HC02_MOE_VC45 $3. ;
              informat HC03_EST_VC45 $10. ;
              informat HC03_MOE_VC45 $10. ;
              informat HC04_EST_VC45 $3. ;
              informat HC04_MOE_VC45 $3. ;
              informat HC05_EST_VC45 $10. ;
              informat HC05_MOE_VC45 $10. ;
              informat HC06_EST_VC45 $3. ;
              informat HC06_MOE_VC45 $3. ;
              informat HC01_EST_VC46 $10. ;
              informat HC01_MOE_VC46 $10. ;
              informat HC02_EST_VC46 $5. ;
              informat HC02_MOE_VC46 $4. ;
              informat HC03_EST_VC46 $10. ;
              informat HC03_MOE_VC46 $10. ;
              informat HC04_EST_VC46 $4. ;
              informat HC04_MOE_VC46 $4. ;
              informat HC05_EST_VC46 $10. ;
              informat HC05_MOE_VC46 $10. ;
              informat HC06_EST_VC46 $5. ;
              informat HC06_MOE_VC46 $4. ;
              informat HC01_EST_VC47 $10. ;
              informat HC01_MOE_VC47 $10. ;
              informat HC02_EST_VC47 $5. ;
              informat HC02_MOE_VC47 $4. ;
              informat HC03_EST_VC47 $10. ;
              informat HC03_MOE_VC47 $10. ;
              informat HC04_EST_VC47 $4. ;
              informat HC04_MOE_VC47 $4. ;
              informat HC05_EST_VC47 $10. ;
              informat HC05_MOE_VC47 $10. ;
              informat HC06_EST_VC47 $5. ;
              informat HC06_MOE_VC47 $4. ;
              informat HC01_EST_VC49 $10. ;
              informat HC01_MOE_VC49 $10. ;
              informat HC02_EST_VC49 $3. ;
              informat HC02_MOE_VC49 $3. ;
              informat HC03_EST_VC49 $10. ;
              informat HC03_MOE_VC49 $10. ;
              informat HC04_EST_VC49 $3. ;
              informat HC04_MOE_VC49 $3. ;
              informat HC05_EST_VC49 $10. ;
              informat HC05_MOE_VC49 $10. ;
              informat HC06_EST_VC49 $3. ;
              informat HC06_MOE_VC49 $3. ;
              informat HC01_EST_VC50 $10. ;
              informat HC01_MOE_VC50 $10. ;
              informat HC02_EST_VC50 $5. ;
              informat HC02_MOE_VC50 $4. ;
              informat HC03_EST_VC50 $10. ;
              informat HC03_MOE_VC50 $10. ;
              informat HC04_EST_VC50 $5. ;
              informat HC04_MOE_VC50 $5. ;
              informat HC05_EST_VC50 $10. ;
              informat HC05_MOE_VC50 $10. ;
              informat HC06_EST_VC50 $5. ;
              informat HC06_MOE_VC50 $5. ;
              informat HC01_EST_VC51 $10. ;
              informat HC01_MOE_VC51 $10. ;
              informat HC02_EST_VC51 $4. ;
              informat HC02_MOE_VC51 $4. ;
              informat HC03_EST_VC51 $10. ;
              informat HC03_MOE_VC51 $10. ;
              informat HC04_EST_VC51 $5. ;
              informat HC04_MOE_VC51 $5. ;
              informat HC05_EST_VC51 $10. ;
              informat HC05_MOE_VC51 $10. ;
              informat HC06_EST_VC51 $5. ;
              informat HC06_MOE_VC51 $5. ;
              informat HC01_EST_VC53 $10. ;
              informat HC01_MOE_VC53 $10. ;
              informat HC02_EST_VC53 $3. ;
              informat HC02_MOE_VC53 $3. ;
              informat HC03_EST_VC53 $10. ;
              informat HC03_MOE_VC53 $10. ;
              informat HC04_EST_VC53 $3. ;
              informat HC04_MOE_VC53 $3. ;
              informat HC05_EST_VC53 $10. ;
              informat HC05_MOE_VC53 $10. ;
              informat HC06_EST_VC53 $3. ;
              informat HC06_MOE_VC53 $3. ;
              informat HC01_EST_VC54 $10. ;
              informat HC01_MOE_VC54 $10. ;
              informat HC02_EST_VC54 $4. ;
              informat HC02_MOE_VC54 $4. ;
              informat HC03_EST_VC54 $10. ;
              informat HC03_MOE_VC54 $10. ;
              informat HC04_EST_VC54 $5. ;
              informat HC04_MOE_VC54 $4. ;
              informat HC05_EST_VC54 $10. ;
              informat HC05_MOE_VC54 $10. ;
              informat HC06_EST_VC54 $4. ;
              informat HC06_MOE_VC54 $4. ;
              informat HC01_EST_VC55 $10. ;
              informat HC01_MOE_VC55 $10. ;
              informat HC02_EST_VC55 $4. ;
              informat HC02_MOE_VC55 $4. ;
              informat HC03_EST_VC55 $10. ;
              informat HC03_MOE_VC55 $10. ;
              informat HC04_EST_VC55 $4. ;
              informat HC04_MOE_VC55 $4. ;
              informat HC05_EST_VC55 $10. ;
              informat HC05_MOE_VC55 $10. ;
              informat HC06_EST_VC55 $4. ;
              informat HC06_MOE_VC55 $4. ;
              informat HC01_EST_VC57 $10. ;
              informat HC01_MOE_VC57 $10. ;
              informat HC02_EST_VC57 $3. ;
              informat HC02_MOE_VC57 $3. ;
              informat HC03_EST_VC57 $10. ;
              informat HC03_MOE_VC57 $10. ;
              informat HC04_EST_VC57 $3. ;
              informat HC04_MOE_VC57 $3. ;
              informat HC05_EST_VC57 $10. ;
							informat HC05_MOE_VC57 $10. ;
              informat HC06_EST_VC57 $3. ;
              informat HC06_MOE_VC57 $3. ;
              informat HC01_EST_VC58 $10. ;
              informat HC01_MOE_VC58 $10. ;
              informat HC02_EST_VC58 $1. ;
              informat HC02_MOE_VC58 $2. ;
              informat HC03_EST_VC58 $10. ;
              informat HC03_MOE_VC58 $10. ;
              informat HC04_EST_VC58 $1. ;
              informat HC04_MOE_VC58 $2. ;
              informat HC05_EST_VC58 $10. ;
              informat HC05_MOE_VC58 $10. ;
              informat HC06_EST_VC58 $1. ;
              informat HC06_MOE_VC58 $2. ;
              informat HC01_EST_VC59 $10. ;
              informat HC01_MOE_VC59 $10. ;
              informat HC02_EST_VC59 $1. ;
              informat HC02_MOE_VC59 $2. ;
              informat HC03_EST_VC59 $10. ;
              informat HC03_MOE_VC59 $10. ;
              informat HC04_EST_VC59 $1. ;
              informat HC04_MOE_VC59 $2. ;
              informat HC05_EST_VC59 $10. ;
              informat HC05_MOE_VC59 $10. ;
              informat HC06_EST_VC59 $1. ;
              informat HC06_MOE_VC59 $2. ;
              informat HC01_EST_VC61 $10. ;
              informat HC01_MOE_VC61 $10. ;
              informat HC02_EST_VC61 $3. ;
              informat HC02_MOE_VC61 $3. ;
              informat HC03_EST_VC61 $10. ;
              informat HC03_MOE_VC61 $10. ;
              informat HC04_EST_VC61 $3. ;
              informat HC04_MOE_VC61 $3. ;
              informat HC05_EST_VC61 $10. ;
              informat HC05_MOE_VC61 $10. ;
              informat HC06_EST_VC61 $3. ;
              informat HC06_MOE_VC61 $3. ;
              informat HC01_EST_VC62 $10. ;
              informat HC01_MOE_VC62 $10. ;
              informat HC02_EST_VC62 $10. ;
              informat HC02_MOE_VC62 $10. ;
              informat HC03_EST_VC62 $10. ;
              informat HC03_MOE_VC62 $10. ;
              informat HC04_EST_VC62 $10. ;
              informat HC04_MOE_VC62 $10. ;
              informat HC05_EST_VC62 $10. ;
              informat HC05_MOE_VC62 $10. ;
              informat HC06_EST_VC62 $10. ;
              informat HC06_MOE_VC62 $10. ;
              informat HC01_EST_VC63 $10. ;
              informat HC01_MOE_VC63 $10. ;
              informat HC02_EST_VC63 $10. ;
              informat HC02_MOE_VC63 $10. ;
              informat HC03_EST_VC63 $10. ;
              informat HC03_MOE_VC63 $10. ;
              informat HC04_EST_VC63 $10. ;
              informat HC04_MOE_VC63 $10. ;
              informat HC05_EST_VC63 $10. ;
              informat HC05_MOE_VC63 $10. ;
              informat HC06_EST_VC63 $10. ;
              informat HC06_MOE_VC63 $10. ;
              informat HC01_EST_VC65 $10. ;
              informat HC01_MOE_VC65 $10. ;
              informat HC02_EST_VC65 $3. ;
              informat HC02_MOE_VC65 $3. ;
              informat HC03_EST_VC65 $10. ;
              informat HC03_MOE_VC65 $10. ;
              informat HC04_EST_VC65 $3. ;
              informat HC04_MOE_VC65 $3. ;
              informat HC05_EST_VC65 $10. ;
              informat HC05_MOE_VC65 $10. ;
              informat HC06_EST_VC65 $3. ;
              informat HC06_MOE_VC65 $3. ;
              informat HC01_EST_VC66 $10. ;
              informat HC01_MOE_VC66 $10. ;
              informat HC02_EST_VC66 $5. ;
              informat HC02_MOE_VC66 $4. ;
              informat HC03_EST_VC66 $10. ;
              informat HC03_MOE_VC66 $10. ;
              informat HC04_EST_VC66 $5. ;
              informat HC04_MOE_VC66 $4. ;
              informat HC05_EST_VC66 $10. ;
              informat HC05_MOE_VC66 $10. ;
              informat HC06_EST_VC66 $5. ;
              informat HC06_MOE_VC66 $4. ;
              informat HC01_EST_VC67 $10. ;
              informat HC01_MOE_VC67 $10. ;
              informat HC02_EST_VC67 $4. ;
              informat HC02_MOE_VC67 $4. ;
              informat HC03_EST_VC67 $10. ;
              informat HC03_MOE_VC67 $10. ;
              informat HC04_EST_VC67 $4. ;
              informat HC04_MOE_VC67 $4. ;
              informat HC05_EST_VC67 $10. ;
              informat HC05_MOE_VC67 $10. ;
              informat HC06_EST_VC67 $4. ;
              informat HC06_MOE_VC67 $4. ;
              informat HC01_EST_VC69 $10. ;
              informat HC01_MOE_VC69 $10. ;
              informat HC02_EST_VC69 $3. ;
              informat HC02_MOE_VC69 $3. ;
              informat HC03_EST_VC69 $10. ;
              informat HC03_MOE_VC69 $10. ;
              informat HC04_EST_VC69 $3. ;
              informat HC04_MOE_VC69 $3. ;
              informat HC05_EST_VC69 $10. ;
              informat HC05_MOE_VC69 $10. ;
              informat HC06_EST_VC69 $3. ;
              informat HC06_MOE_VC69 $3. ;
              informat HC01_EST_VC70 $10. ;
              informat HC01_MOE_VC70 $10. ;
              informat HC02_EST_VC70 $10. ;
              informat HC02_MOE_VC70 $10. ;
              informat HC03_EST_VC70 $10. ;
              informat HC03_MOE_VC70 $10. ;
              informat HC04_EST_VC70 $10. ;
              informat HC04_MOE_VC70 $10. ;
              informat HC05_EST_VC70 $10. ;
              informat HC05_MOE_VC70 $10. ;
              informat HC06_EST_VC70 $10. ;
              informat HC06_MOE_VC70 $10. ;
              informat HC01_EST_VC71 $10. ;
              informat HC01_MOE_VC71 $10. ;
              informat HC02_EST_VC71 $10. ;
              informat HC02_MOE_VC71 $10. ;
              informat HC03_EST_VC71 $10. ;
              informat HC03_MOE_VC71 $10. ;
              informat HC04_EST_VC71 $10. ;
              informat HC04_MOE_VC71 $10. ;
              informat HC05_EST_VC71 $10. ;
              informat HC05_MOE_VC71 $10. ;
              informat HC06_EST_VC71 $10. ;
              informat HC06_MOE_VC71 $10. ;
              informat HC01_EST_VC74 $3. ;
              informat HC01_MOE_VC74 $3. ;
              informat HC02_EST_VC74 $10. ;
              informat HC02_MOE_VC74 $10. ;
              informat HC03_EST_VC74 $3. ;
              informat HC03_MOE_VC74 $3. ;
              informat HC04_EST_VC74 $10. ;
              informat HC04_MOE_VC74 $10. ;
              informat HC05_EST_VC74 $3. ;
              informat HC05_MOE_VC74 $3. ;
              informat HC06_EST_VC74 $10. ;
              informat HC06_MOE_VC74 $10. ;
              informat HC01_EST_VC75 $3. ;
              informat HC01_MOE_VC75 $3. ;
              informat HC02_EST_VC75 $10. ;
              informat HC02_MOE_VC75 $10. ;
              informat HC03_EST_VC75 $3. ;
              informat HC03_MOE_VC75 $3. ;
              informat HC04_EST_VC75 $10. ;
              informat HC04_MOE_VC75 $10. ;
              informat HC05_EST_VC75 $3. ;
              informat HC05_MOE_VC75 $3. ;
              informat HC06_EST_VC75 $10. ;
              informat HC06_MOE_VC75 $10. ;
              informat HC01_EST_VC76 $3. ;
              informat HC01_MOE_VC76 $3. ;
              informat HC02_EST_VC76 $10. ;
              informat HC02_MOE_VC76 $10. ;
              informat HC03_EST_VC76 $3. ;
              informat HC03_MOE_VC76 $3. ;
              informat HC04_EST_VC76 $10. ;
              informat HC04_MOE_VC76 $10. ;
              informat HC05_EST_VC76 $3. ;
              informat HC05_MOE_VC76 $3. ;
              informat HC06_EST_VC76 $10. ;
              informat HC06_MOE_VC76 $10. ;
              informat HC01_EST_VC77 $3. ;
              informat HC01_MOE_VC77 $3. ;
              informat HC02_EST_VC77 $10. ;
              informat HC02_MOE_VC77 $10. ;
              informat HC03_EST_VC77 $3. ;
              informat HC03_MOE_VC77 $3. ;
              informat HC04_EST_VC77 $10. ;
              informat HC04_MOE_VC77 $10. ;
              informat HC05_EST_VC77 $3. ;
              informat HC05_MOE_VC77 $3. ;
              informat HC06_EST_VC77 $10. ;
              informat HC06_MOE_VC77 $10. ;
              informat HC01_EST_VC80 $10. ;
              informat HC01_MOE_VC80 $10. ;
              informat HC02_EST_VC80 $3. ;
              informat HC02_MOE_VC80 $3. ;
              informat HC03_EST_VC80 $10. ;
              informat HC03_MOE_VC80 $10. ;
              informat HC04_EST_VC80 $3. ;
              informat HC04_MOE_VC80 $3. ;
              informat HC05_EST_VC80 $10. ;
              informat HC05_MOE_VC80 $10. ;
              informat HC06_EST_VC80 $3. ;
              informat HC06_MOE_VC80 $3. ;
              informat HC01_EST_VC81 $5. ;
              informat HC01_MOE_VC81 $4. ;
              informat HC02_EST_VC81 $3. ;
							informat HC02_MOE_VC81 $3. ;
              informat HC03_EST_VC81 $5. ;
              informat HC03_MOE_VC81 $5. ;
              informat HC04_EST_VC81 $3. ;
              informat HC04_MOE_VC81 $3. ;
              informat HC05_EST_VC81 $5. ;
              informat HC05_MOE_VC81 $5. ;
              informat HC06_EST_VC81 $3. ;
              informat HC06_MOE_VC81 $3. ;
              informat HC01_EST_VC82 $10. ;
              informat HC01_MOE_VC82 $10. ;
              informat HC02_EST_VC82 $3. ;
              informat HC02_MOE_VC82 $3. ;
              informat HC03_EST_VC82 $5. ;
              informat HC03_MOE_VC82 $4. ;
              informat HC04_EST_VC82 $3. ;
              informat HC04_MOE_VC82 $3. ;
              informat HC05_EST_VC82 $5. ;
              informat HC05_MOE_VC82 $5. ;
              informat HC06_EST_VC82 $3. ;
              informat HC06_MOE_VC82 $3. ;
              informat HC01_EST_VC83 $10. ;
              informat HC01_MOE_VC83 $10. ;
              informat HC02_EST_VC83 $3. ;
              informat HC02_MOE_VC83 $3. ;
              informat HC03_EST_VC83 $5. ;
              informat HC03_MOE_VC83 $5. ;
              informat HC04_EST_VC83 $3. ;
              informat HC04_MOE_VC83 $3. ;
              informat HC05_EST_VC83 $5. ;
              informat HC05_MOE_VC83 $4. ;
              informat HC06_EST_VC83 $3. ;
              informat HC06_MOE_VC83 $3. ;
              informat HC01_EST_VC84 $10. ;
              informat HC01_MOE_VC84 $10. ;
              informat HC02_EST_VC84 $3. ;
              informat HC02_MOE_VC84 $3. ;
              informat HC03_EST_VC84 $5. ;
              informat HC03_MOE_VC84 $5. ;
              informat HC04_EST_VC84 $3. ;
              informat HC04_MOE_VC84 $3. ;
              informat HC05_EST_VC84 $10. ;
              informat HC05_MOE_VC84 $10. ;
              informat HC06_EST_VC84 $3. ;
              informat HC06_MOE_VC84 $3. ;
              informat HC01_EST_VC85 $5. ;
              informat HC01_MOE_VC85 $5. ;
              informat HC02_EST_VC85 $3. ;
              informat HC02_MOE_VC85 $3. ;
              informat HC03_EST_VC85 $5. ;
              informat HC03_MOE_VC85 $5. ;
              informat HC04_EST_VC85 $3. ;
              informat HC04_MOE_VC85 $3. ;
              informat HC05_EST_VC85 $5. ;
              informat HC05_MOE_VC85 $5. ;
              informat HC06_EST_VC85 $3. ;
              informat HC06_MOE_VC85 $3. ;
              format GEO_id $14. ;
              format GEO_id2 $10. ;
              format GEO_display_label $11. ;
              format HC01_EST_VC02 $10. ;
              format HC01_MOE_VC02 $5. ;
              format HC02_EST_VC02 $3. ;
              format HC02_MOE_VC02 $3. ;
              format HC03_EST_VC02 $10. ;
              format HC03_MOE_VC02 $5. ;
              format HC04_EST_VC02 $3. ;
              format HC04_MOE_VC02 $3. ;
              format HC05_EST_VC02 $10. ;
              format HC05_MOE_VC02 $5. ;
              format HC06_EST_VC02 $3. ;
              format HC06_MOE_VC02 $3. ;
              format HC01_EST_VC03 $10. ;
              format HC01_MOE_VC03 $10. ;
              format HC02_EST_VC03 $10. ;
              format HC02_MOE_VC03 $10. ;
              format HC03_EST_VC03 $10. ;
              format HC03_MOE_VC03 $10. ;
              format HC04_EST_VC03 $10. ;
              format HC04_MOE_VC03 $10. ;
              format HC05_EST_VC03 $10. ;
              format HC05_MOE_VC03 $10. ;
              format HC06_EST_VC03 $10. ;
              format HC06_MOE_VC03 $10. ;
              format HC01_EST_VC04 $10. ;
              format HC01_MOE_VC04 $10. ;
              format HC02_EST_VC04 $10. ;
              format HC02_MOE_VC04 $10. ;
              format HC03_EST_VC04 $10. ;
              format HC03_MOE_VC04 $10. ;
              format HC04_EST_VC04 $10. ;
              format HC04_MOE_VC04 $10. ;
              format HC05_EST_VC04 $10. ;
              format HC05_MOE_VC04 $10. ;
              format HC06_EST_VC04 $10. ;
              format HC06_MOE_VC04 $10. ;
              format HC01_EST_VC05 $10. ;
              format HC01_MOE_VC05 $10. ;
              format HC02_EST_VC05 $10. ;
              format HC02_MOE_VC05 $10. ;
              format HC03_EST_VC05 $10. ;
              format HC03_MOE_VC05 $10. ;
              format HC04_EST_VC05 $10. ;
              format HC04_MOE_VC05 $10. ;
              format HC05_EST_VC05 $10. ;
              format HC05_MOE_VC05 $10. ;
              format HC06_EST_VC05 $10. ;
              format HC06_MOE_VC05 $10. ;
              format HC01_EST_VC06 $10. ;
              format HC01_MOE_VC06 $10. ;
              format HC02_EST_VC06 $10. ;
              format HC02_MOE_VC06 $10. ;
              format HC03_EST_VC06 $10. ;
              format HC03_MOE_VC06 $10. ;
              format HC04_EST_VC06 $10. ;
              format HC04_MOE_VC06 $10. ;
              format HC05_EST_VC06 $10. ;
              format HC05_MOE_VC06 $10. ;
              format HC06_EST_VC06 $10. ;
              format HC06_MOE_VC06 $10. ;
              format HC01_EST_VC08 $10. ;
              format HC01_MOE_VC08 $5. ;
              format HC02_EST_VC08 $3. ;
              format HC02_MOE_VC08 $3. ;
              format HC03_EST_VC08 $10. ;
              format HC03_MOE_VC08 $5. ;
              format HC04_EST_VC08 $3. ;
              format HC04_MOE_VC08 $3. ;
              format HC05_EST_VC08 $10. ;
              format HC05_MOE_VC08 $5. ;
              format HC06_EST_VC08 $3. ;
              format HC06_MOE_VC08 $3. ;
              format HC01_EST_VC09 $10. ;
              format HC01_MOE_VC09 $10. ;
              format HC02_EST_VC09 $10. ;
              format HC02_MOE_VC09 $10. ;
              format HC03_EST_VC09 $10. ;
              format HC03_MOE_VC09 $10. ;
              format HC04_EST_VC09 $10. ;
              format HC04_MOE_VC09 $10. ;
              format HC05_EST_VC09 $10. ;
              format HC05_MOE_VC09 $10. ;
              format HC06_EST_VC09 $10. ;
              format HC06_MOE_VC09 $10. ;
              format HC01_EST_VC10 $10. ;
              format HC01_MOE_VC10 $10. ;
              format HC02_EST_VC10 $10. ;
              format HC02_MOE_VC10 $10. ;
              format HC03_EST_VC10 $10. ;
              format HC03_MOE_VC10 $10. ;
              format HC04_EST_VC10 $10. ;
              format HC04_MOE_VC10 $10. ;
              format HC05_EST_VC10 $10. ;
              format HC05_MOE_VC10 $10. ;
              format HC06_EST_VC10 $10. ;
              format HC06_MOE_VC10 $10. ;
              format HC01_EST_VC11 $10. ;
              format HC01_MOE_VC11 $10. ;
              format HC02_EST_VC11 $10. ;
              format HC02_MOE_VC11 $10. ;
              format HC03_EST_VC11 $10. ;
              format HC03_MOE_VC11 $10. ;
              format HC04_EST_VC11 $10. ;
              format HC04_MOE_VC11 $10. ;
              format HC05_EST_VC11 $10. ;
              format HC05_MOE_VC11 $10. ;
              format HC06_EST_VC11 $10. ;
              format HC06_MOE_VC11 $10. ;
              format HC01_EST_VC12 $10. ;
              format HC01_MOE_VC12 $10. ;
              format HC02_EST_VC12 $10. ;
              format HC02_MOE_VC12 $10. ;
              format HC03_EST_VC12 $10. ;
              format HC03_MOE_VC12 $10. ;
              format HC04_EST_VC12 $10. ;
              format HC04_MOE_VC12 $10. ;
              format HC05_EST_VC12 $10. ;
              format HC05_MOE_VC12 $10. ;
              format HC06_EST_VC12 $10. ;
              format HC06_MOE_VC12 $10. ;
              format HC01_EST_VC13 $10. ;
              format HC01_MOE_VC13 $10. ;
              format HC02_EST_VC13 $10. ;
              format HC02_MOE_VC13 $10. ;
              format HC03_EST_VC13 $10. ;
              format HC03_MOE_VC13 $10. ;
              format HC04_EST_VC13 $10. ;
              format HC04_MOE_VC13 $10. ;
              format HC05_EST_VC13 $10. ;
              format HC05_MOE_VC13 $10. ;
              format HC06_EST_VC13 $10. ;
              format HC06_MOE_VC13 $10. ;
              format HC01_EST_VC14 $10. ;
              format HC01_MOE_VC14 $10. ;
              format HC02_EST_VC14 $10. ;
              format HC02_MOE_VC14 $10. ;
              format HC03_EST_VC14 $10. ;
              format HC03_MOE_VC14 $10. ;
							format HC04_EST_VC14 $10. ;
              format HC04_MOE_VC14 $10. ;
              format HC05_EST_VC14 $10. ;
              format HC05_MOE_VC14 $10. ;
              format HC06_EST_VC14 $10. ;
              format HC06_MOE_VC14 $10. ;
              format HC01_EST_VC15 $10. ;
              format HC01_MOE_VC15 $10. ;
              format HC02_EST_VC15 $10. ;
              format HC02_MOE_VC15 $10. ;
              format HC03_EST_VC15 $10. ;
              format HC03_MOE_VC15 $10. ;
              format HC04_EST_VC15 $10. ;
              format HC04_MOE_VC15 $10. ;
              format HC05_EST_VC15 $10. ;
              format HC05_MOE_VC15 $10. ;
              format HC06_EST_VC15 $10. ;
              format HC06_MOE_VC15 $10. ;
              format HC01_EST_VC17 $3. ;
              format HC01_MOE_VC17 $3. ;
              format HC02_EST_VC17 $10. ;
              format HC02_MOE_VC17 $10. ;
              format HC03_EST_VC17 $3. ;
              format HC03_MOE_VC17 $3. ;
              format HC04_EST_VC17 $10. ;
              format HC04_MOE_VC17 $10. ;
              format HC05_EST_VC17 $3. ;
              format HC05_MOE_VC17 $3. ;
              format HC06_EST_VC17 $10. ;
              format HC06_MOE_VC17 $10. ;
              format HC01_EST_VC18 $3. ;
              format HC01_MOE_VC18 $3. ;
              format HC02_EST_VC18 $10. ;
              format HC02_MOE_VC18 $10. ;
              format HC03_EST_VC18 $3. ;
              format HC03_MOE_VC18 $3. ;
              format HC04_EST_VC18 $10. ;
              format HC04_MOE_VC18 $10. ;
              format HC05_EST_VC18 $3. ;
              format HC05_MOE_VC18 $3. ;
              format HC06_EST_VC18 $10. ;
              format HC06_MOE_VC18 $10. ;
              format HC01_EST_VC20 $10. ;
              format HC01_MOE_VC20 $5. ;
              format HC02_EST_VC20 $3. ;
              format HC02_MOE_VC20 $3. ;
              format HC03_EST_VC20 $10. ;
              format HC03_MOE_VC20 $5. ;
              format HC04_EST_VC20 $3. ;
              format HC04_MOE_VC20 $3. ;
              format HC05_EST_VC20 $10. ;
              format HC05_MOE_VC20 $5. ;
              format HC06_EST_VC20 $3. ;
              format HC06_MOE_VC20 $3. ;
              format HC01_EST_VC21 $10. ;
              format HC01_MOE_VC21 $10. ;
              format HC02_EST_VC21 $10. ;
              format HC02_MOE_VC21 $10. ;
              format HC03_EST_VC21 $10. ;
              format HC03_MOE_VC21 $10. ;
              format HC04_EST_VC21 $10. ;
              format HC04_MOE_VC21 $10. ;
              format HC05_EST_VC21 $10. ;
              format HC05_MOE_VC21 $10. ;
              format HC06_EST_VC21 $10. ;
              format HC06_MOE_VC21 $10. ;
              format HC01_EST_VC22 $10. ;
              format HC01_MOE_VC22 $10. ;
              format HC02_EST_VC22 $10. ;
              format HC02_MOE_VC22 $10. ;
              format HC03_EST_VC22 $10. ;
              format HC03_MOE_VC22 $10. ;
              format HC04_EST_VC22 $10. ;
              format HC04_MOE_VC22 $10. ;
              format HC05_EST_VC22 $10. ;
              format HC05_MOE_VC22 $10. ;
              format HC06_EST_VC22 $10. ;
              format HC06_MOE_VC22 $10. ;
              format HC01_EST_VC24 $10. ;
              format HC01_MOE_VC24 $5. ;
              format HC02_EST_VC24 $3. ;
              format HC02_MOE_VC24 $3. ;
              format HC03_EST_VC24 $10. ;
              format HC03_MOE_VC24 $5. ;
              format HC04_EST_VC24 $3. ;
              format HC04_MOE_VC24 $3. ;
              format HC05_EST_VC24 $10. ;
              format HC05_MOE_VC24 $5. ;
              format HC06_EST_VC24 $3. ;
              format HC06_MOE_VC24 $3. ;
              format HC01_EST_VC25 $10. ;
              format HC01_MOE_VC25 $10. ;
              format HC02_EST_VC25 $10. ;
              format HC02_MOE_VC25 $10. ;
              format HC03_EST_VC25 $10. ;
              format HC03_MOE_VC25 $10. ;
              format HC04_EST_VC25 $10. ;
              format HC04_MOE_VC25 $10. ;
              format HC05_EST_VC25 $10. ;
              format HC05_MOE_VC25 $10. ;
              format HC06_EST_VC25 $10. ;
              format HC06_MOE_VC25 $10. ;
              format HC01_EST_VC26 $10. ;
              format HC01_MOE_VC26 $10. ;
              format HC02_EST_VC26 $10. ;
              format HC02_MOE_VC26 $10. ;
              format HC03_EST_VC26 $10. ;
              format HC03_MOE_VC26 $10. ;
              format HC04_EST_VC26 $10. ;
              format HC04_MOE_VC26 $10. ;
              format HC05_EST_VC26 $10. ;
              format HC05_MOE_VC26 $10. ;
              format HC06_EST_VC26 $10. ;
              format HC06_MOE_VC26 $10. ;
              format HC01_EST_VC28 $10. ;
              format HC01_MOE_VC28 $5. ;
              format HC02_EST_VC28 $3. ;
              format HC02_MOE_VC28 $3. ;
              format HC03_EST_VC28 $10. ;
              format HC03_MOE_VC28 $5. ;
              format HC04_EST_VC28 $3. ;
              format HC04_MOE_VC28 $3. ;
              format HC05_EST_VC28 $10. ;
              format HC05_MOE_VC28 $5. ;
              format HC06_EST_VC28 $3. ;
              format HC06_MOE_VC28 $3. ;
              format HC01_EST_VC29 $10. ;
              format HC01_MOE_VC29 $10. ;
              format HC02_EST_VC29 $10. ;
              format HC02_MOE_VC29 $10. ;
              format HC03_EST_VC29 $10. ;
              format HC03_MOE_VC29 $10. ;
              format HC04_EST_VC29 $10. ;
              format HC04_MOE_VC29 $10. ;
              format HC05_EST_VC29 $10. ;
              format HC05_MOE_VC29 $10. ;
              format HC06_EST_VC29 $10. ;
              format HC06_MOE_VC29 $10. ;
              format HC01_EST_VC30 $10. ;
              format HC01_MOE_VC30 $10. ;
              format HC02_EST_VC30 $10. ;
              format HC02_MOE_VC30 $10. ;
              format HC03_EST_VC30 $10. ;
              format HC03_MOE_VC30 $10. ;
              format HC04_EST_VC30 $10. ;
              format HC04_MOE_VC30 $10. ;
              format HC05_EST_VC30 $10. ;
              format HC05_MOE_VC30 $10. ;
              format HC06_EST_VC30 $10. ;
              format HC06_MOE_VC30 $10. ;
              format HC01_EST_VC32 $10. ;
              format HC01_MOE_VC32 $5. ;
              format HC02_EST_VC32 $3. ;
              format HC02_MOE_VC32 $3. ;
              format HC03_EST_VC32 $10. ;
              format HC03_MOE_VC32 $5. ;
              format HC04_EST_VC32 $3. ;
              format HC04_MOE_VC32 $3. ;
              format HC05_EST_VC32 $10. ;
              format HC05_MOE_VC32 $5. ;
              format HC06_EST_VC32 $3. ;
              format HC06_MOE_VC32 $3. ;
              format HC01_EST_VC33 $10. ;
              format HC01_MOE_VC33 $10. ;
              format HC02_EST_VC33 $10. ;
              format HC02_MOE_VC33 $10. ;
              format HC03_EST_VC33 $10. ;
              format HC03_MOE_VC33 $10. ;
              format HC04_EST_VC33 $10. ;
              format HC04_MOE_VC33 $10. ;
              format HC05_EST_VC33 $10. ;
              format HC05_MOE_VC33 $10. ;
              format HC06_EST_VC33 $10. ;
              format HC06_MOE_VC33 $10. ;
              format HC01_EST_VC34 $10. ;
              format HC01_MOE_VC34 $10. ;
              format HC02_EST_VC34 $10. ;
              format HC02_MOE_VC34 $10. ;
              format HC03_EST_VC34 $10. ;
              format HC03_MOE_VC34 $10. ;
              format HC04_EST_VC34 $10. ;
              format HC04_MOE_VC34 $10. ;
              format HC05_EST_VC34 $10. ;
              format HC05_MOE_VC34 $10. ;
              format HC06_EST_VC34 $10. ;
              format HC06_MOE_VC34 $10. ;
              format HC01_EST_VC37 $10. ;
              format HC01_MOE_VC37 $10. ;
              format HC02_EST_VC37 $3. ;
              format HC02_MOE_VC37 $3. ;
              format HC03_EST_VC37 $10. ;
              format HC03_MOE_VC37 $10. ;
              format HC04_EST_VC37 $3. ;
              format HC04_MOE_VC37 $3. ;
              format HC05_EST_VC37 $10. ;
              format HC05_MOE_VC37 $10. ;
              format HC06_EST_VC37 $3. ;
              format HC06_MOE_VC37 $3. ;
							format HC01_EST_VC38 $10. ;
              format HC01_MOE_VC38 $10. ;
              format HC02_EST_VC38 $10. ;
              format HC02_MOE_VC38 $10. ;
              format HC03_EST_VC38 $10. ;
              format HC03_MOE_VC38 $10. ;
              format HC04_EST_VC38 $10. ;
              format HC04_MOE_VC38 $10. ;
              format HC05_EST_VC38 $10. ;
              format HC05_MOE_VC38 $10. ;
              format HC06_EST_VC38 $10. ;
              format HC06_MOE_VC38 $10. ;
              format HC01_EST_VC39 $10. ;
              format HC01_MOE_VC39 $10. ;
              format HC02_EST_VC39 $10. ;
              format HC02_MOE_VC39 $10. ;
              format HC03_EST_VC39 $10. ;
              format HC03_MOE_VC39 $10. ;
              format HC04_EST_VC39 $10. ;
              format HC04_MOE_VC39 $10. ;
              format HC05_EST_VC39 $10. ;
              format HC05_MOE_VC39 $10. ;
              format HC06_EST_VC39 $10. ;
              format HC06_MOE_VC39 $10. ;
              format HC01_EST_VC41 $10. ;
              format HC01_MOE_VC41 $10. ;
              format HC02_EST_VC41 $3. ;
              format HC02_MOE_VC41 $3. ;
              format HC03_EST_VC41 $10. ;
              format HC03_MOE_VC41 $10. ;
              format HC04_EST_VC41 $3. ;
              format HC04_MOE_VC41 $3. ;
              format HC05_EST_VC41 $10. ;
              format HC05_MOE_VC41 $10. ;
              format HC06_EST_VC41 $3. ;
              format HC06_MOE_VC41 $3. ;
              format HC01_EST_VC42 $10. ;
              format HC01_MOE_VC42 $10. ;
              format HC02_EST_VC42 $5. ;
              format HC02_MOE_VC42 $4. ;
              format HC03_EST_VC42 $10. ;
              format HC03_MOE_VC42 $10. ;
              format HC04_EST_VC42 $5. ;
              format HC04_MOE_VC42 $5. ;
              format HC05_EST_VC42 $10. ;
              format HC05_MOE_VC42 $10. ;
              format HC06_EST_VC42 $5. ;
              format HC06_MOE_VC42 $4. ;
              format HC01_EST_VC43 $10. ;
              format HC01_MOE_VC43 $10. ;
              format HC02_EST_VC43 $5. ;
              format HC02_MOE_VC43 $4. ;
              format HC03_EST_VC43 $10. ;
              format HC03_MOE_VC43 $10. ;
              format HC04_EST_VC43 $5. ;
              format HC04_MOE_VC43 $5. ;
              format HC05_EST_VC43 $10. ;
              format HC05_MOE_VC43 $10. ;
              format HC06_EST_VC43 $5. ;
              format HC06_MOE_VC43 $4. ;
              format HC01_EST_VC45 $10. ;
              format HC01_MOE_VC45 $10. ;
              format HC02_EST_VC45 $3. ;
              format HC02_MOE_VC45 $3. ;
              format HC03_EST_VC45 $10. ;
              format HC03_MOE_VC45 $10. ;
              format HC04_EST_VC45 $3. ;
              format HC04_MOE_VC45 $3. ;
              format HC05_EST_VC45 $10. ;
              format HC05_MOE_VC45 $10. ;
              format HC06_EST_VC45 $3. ;
              format HC06_MOE_VC45 $3. ;
              format HC01_EST_VC46 $10. ;
              format HC01_MOE_VC46 $10. ;
              format HC02_EST_VC46 $5. ;
              format HC02_MOE_VC46 $4. ;
              format HC03_EST_VC46 $10. ;
              format HC03_MOE_VC46 $10. ;
              format HC04_EST_VC46 $4. ;
              format HC04_MOE_VC46 $4. ;
              format HC05_EST_VC46 $10. ;
              format HC05_MOE_VC46 $10. ;
              format HC06_EST_VC46 $5. ;
              format HC06_MOE_VC46 $4. ;
              format HC01_EST_VC47 $10. ;
              format HC01_MOE_VC47 $10. ;
              format HC02_EST_VC47 $5. ;
              format HC02_MOE_VC47 $4. ;
              format HC03_EST_VC47 $10. ;
              format HC03_MOE_VC47 $10. ;
              format HC04_EST_VC47 $4. ;
              format HC04_MOE_VC47 $4. ;
              format HC05_EST_VC47 $10. ;
              format HC05_MOE_VC47 $10. ;
              format HC06_EST_VC47 $5. ;
              format HC06_MOE_VC47 $4. ;
              format HC01_EST_VC49 $10. ;
              format HC01_MOE_VC49 $10. ;
              format HC02_EST_VC49 $3. ;
              format HC02_MOE_VC49 $3. ;
              format HC03_EST_VC49 $10. ;
              format HC03_MOE_VC49 $10. ;
              format HC04_EST_VC49 $3. ;
              format HC04_MOE_VC49 $3. ;
              format HC05_EST_VC49 $10. ;
              format HC05_MOE_VC49 $10. ;
              format HC06_EST_VC49 $3. ;
              format HC06_MOE_VC49 $3. ;
              format HC01_EST_VC50 $10. ;
              format HC01_MOE_VC50 $10. ;
              format HC02_EST_VC50 $5. ;
              format HC02_MOE_VC50 $4. ;
              format HC03_EST_VC50 $10. ;
              format HC03_MOE_VC50 $10. ;
              format HC04_EST_VC50 $5. ;
              format HC04_MOE_VC50 $5. ;
              format HC05_EST_VC50 $10. ;
              format HC05_MOE_VC50 $10. ;
              format HC06_EST_VC50 $5. ;
              format HC06_MOE_VC50 $5. ;
              format HC01_EST_VC51 $10. ;
              format HC01_MOE_VC51 $10. ;
              format HC02_EST_VC51 $4. ;
              format HC02_MOE_VC51 $4. ;
              format HC03_EST_VC51 $10. ;
              format HC03_MOE_VC51 $10. ;
              format HC04_EST_VC51 $5. ;
              format HC04_MOE_VC51 $5. ;
              format HC05_EST_VC51 $10. ;
              format HC05_MOE_VC51 $10. ;
              format HC06_EST_VC51 $5. ;
              format HC06_MOE_VC51 $5. ;
              format HC01_EST_VC53 $10. ;
              format HC01_MOE_VC53 $10. ;
              format HC02_EST_VC53 $3. ;
              format HC02_MOE_VC53 $3. ;
              format HC03_EST_VC53 $10. ;
              format HC03_MOE_VC53 $10. ;
              format HC04_EST_VC53 $3. ;
              format HC04_MOE_VC53 $3. ;
              format HC05_EST_VC53 $10. ;
              format HC05_MOE_VC53 $10. ;
              format HC06_EST_VC53 $3. ;
              format HC06_MOE_VC53 $3. ;
              format HC01_EST_VC54 $10. ;
              format HC01_MOE_VC54 $10. ;
              format HC02_EST_VC54 $4. ;
              format HC02_MOE_VC54 $4. ;
              format HC03_EST_VC54 $10. ;
              format HC03_MOE_VC54 $10. ;
              format HC04_EST_VC54 $5. ;
              format HC04_MOE_VC54 $4. ;
              format HC05_EST_VC54 $10. ;
              format HC05_MOE_VC54 $10. ;
              format HC06_EST_VC54 $4. ;
              format HC06_MOE_VC54 $4. ;
              format HC01_EST_VC55 $10. ;
              format HC01_MOE_VC55 $10. ;
              format HC02_EST_VC55 $4. ;
              format HC02_MOE_VC55 $4. ;
              format HC03_EST_VC55 $10. ;
              format HC03_MOE_VC55 $10. ;
              format HC04_EST_VC55 $4. ;
              format HC04_MOE_VC55 $4. ;
              format HC05_EST_VC55 $10. ;
              format HC05_MOE_VC55 $10. ;
              format HC06_EST_VC55 $4. ;
              format HC06_MOE_VC55 $4. ;
              format HC01_EST_VC57 $10. ;
              format HC01_MOE_VC57 $10. ;
              format HC02_EST_VC57 $3. ;
              format HC02_MOE_VC57 $3. ;
              format HC03_EST_VC57 $10. ;
              format HC03_MOE_VC57 $10. ;
              format HC04_EST_VC57 $3. ;
              format HC04_MOE_VC57 $3. ;
              format HC05_EST_VC57 $10. ;
              format HC05_MOE_VC57 $10. ;
              format HC06_EST_VC57 $3. ;
              format HC06_MOE_VC57 $3. ;
              format HC01_EST_VC58 $10. ;
              format HC01_MOE_VC58 $10. ;
              format HC02_EST_VC58 $1. ;
              format HC02_MOE_VC58 $2. ;
              format HC03_EST_VC58 $10. ;
              format HC03_MOE_VC58 $10. ;
              format HC04_EST_VC58 $1. ;
              format HC04_MOE_VC58 $2. ;
              format HC05_EST_VC58 $10. ;
              format HC05_MOE_VC58 $10. ;
              format HC06_EST_VC58 $1. ;
              format HC06_MOE_VC58 $2. ;
              format HC01_EST_VC59 $10. ;
              format HC01_MOE_VC59 $10. ;
              format HC02_EST_VC59 $1. ;
              format HC02_MOE_VC59 $2. ;
              format HC03_EST_VC59 $10. ;
              format HC03_MOE_VC59 $10. ;
							format HC04_EST_VC59 $1. ;
              format HC04_MOE_VC59 $2. ;
              format HC05_EST_VC59 $10. ;
              format HC05_MOE_VC59 $10. ;
              format HC06_EST_VC59 $1. ;
              format HC06_MOE_VC59 $2. ;
              format HC01_EST_VC61 $10. ;
              format HC01_MOE_VC61 $10. ;
              format HC02_EST_VC61 $3. ;
              format HC02_MOE_VC61 $3. ;
              format HC03_EST_VC61 $10. ;
              format HC03_MOE_VC61 $10. ;
              format HC04_EST_VC61 $3. ;
              format HC04_MOE_VC61 $3. ;
              format HC05_EST_VC61 $10. ;
              format HC05_MOE_VC61 $10. ;
              format HC06_EST_VC61 $3. ;
              format HC06_MOE_VC61 $3. ;
              format HC01_EST_VC62 $10. ;
              format HC01_MOE_VC62 $10. ;
              format HC02_EST_VC62 $10. ;
              format HC02_MOE_VC62 $10. ;
              format HC03_EST_VC62 $10. ;
              format HC03_MOE_VC62 $10. ;
              format HC04_EST_VC62 $10. ;
              format HC04_MOE_VC62 $10. ;
              format HC05_EST_VC62 $10. ;
              format HC05_MOE_VC62 $10. ;
              format HC06_EST_VC62 $10. ;
              format HC06_MOE_VC62 $10. ;
              format HC01_EST_VC63 $10. ;
              format HC01_MOE_VC63 $10. ;
              format HC02_EST_VC63 $10. ;
              format HC02_MOE_VC63 $10. ;
              format HC03_EST_VC63 $10. ;
              format HC03_MOE_VC63 $10. ;
              format HC04_EST_VC63 $10. ;
              format HC04_MOE_VC63 $10. ;
              format HC05_EST_VC63 $10. ;
              format HC05_MOE_VC63 $10. ;
              format HC06_EST_VC63 $10. ;
              format HC06_MOE_VC63 $10. ;
              format HC01_EST_VC65 $10. ;
              format HC01_MOE_VC65 $10. ;
              format HC02_EST_VC65 $3. ;
              format HC02_MOE_VC65 $3. ;
              format HC03_EST_VC65 $10. ;
              format HC03_MOE_VC65 $10. ;
              format HC04_EST_VC65 $3. ;
              format HC04_MOE_VC65 $3. ;
              format HC05_EST_VC65 $10. ;
              format HC05_MOE_VC65 $10. ;
              format HC06_EST_VC65 $3. ;
              format HC06_MOE_VC65 $3. ;
              format HC01_EST_VC66 $10. ;
              format HC01_MOE_VC66 $10. ;
              format HC02_EST_VC66 $5. ;
              format HC02_MOE_VC66 $4. ;
              format HC03_EST_VC66 $10. ;
              format HC03_MOE_VC66 $10. ;
              format HC04_EST_VC66 $5. ;
              format HC04_MOE_VC66 $4. ;
              format HC05_EST_VC66 $10. ;
              format HC05_MOE_VC66 $10. ;
              format HC06_EST_VC66 $5. ;
              format HC06_MOE_VC66 $4. ;
              format HC01_EST_VC67 $10. ;
              format HC01_MOE_VC67 $10. ;
              format HC02_EST_VC67 $4. ;
              format HC02_MOE_VC67 $4. ;
              format HC03_EST_VC67 $10. ;
              format HC03_MOE_VC67 $10. ;
              format HC04_EST_VC67 $4. ;
              format HC04_MOE_VC67 $4. ;
              format HC05_EST_VC67 $10. ;
              format HC05_MOE_VC67 $10. ;
              format HC06_EST_VC67 $4. ;
              format HC06_MOE_VC67 $4. ;
              format HC01_EST_VC69 $10. ;
              format HC01_MOE_VC69 $10. ;
              format HC02_EST_VC69 $3. ;
              format HC02_MOE_VC69 $3. ;
              format HC03_EST_VC69 $10. ;
              format HC03_MOE_VC69 $10. ;
              format HC04_EST_VC69 $3. ;
              format HC04_MOE_VC69 $3. ;
              format HC05_EST_VC69 $10. ;
              format HC05_MOE_VC69 $10. ;
              format HC06_EST_VC69 $3. ;
              format HC06_MOE_VC69 $3. ;
              format HC01_EST_VC70 $10. ;
              format HC01_MOE_VC70 $10. ;
              format HC02_EST_VC70 $10. ;
              format HC02_MOE_VC70 $10. ;
              format HC03_EST_VC70 $10. ;
              format HC03_MOE_VC70 $10. ;
              format HC04_EST_VC70 $10. ;
              format HC04_MOE_VC70 $10. ;
              format HC05_EST_VC70 $10. ;
              format HC05_MOE_VC70 $10. ;
              format HC06_EST_VC70 $10. ;
              format HC06_MOE_VC70 $10. ;
              format HC01_EST_VC71 $10. ;
              format HC01_MOE_VC71 $10. ;
              format HC02_EST_VC71 $10. ;
              format HC02_MOE_VC71 $10. ;
              format HC03_EST_VC71 $10. ;
              format HC03_MOE_VC71 $10. ;
              format HC04_EST_VC71 $10. ;
              format HC04_MOE_VC71 $10. ;
              format HC05_EST_VC71 $10. ;
              format HC05_MOE_VC71 $10. ;
              format HC06_EST_VC71 $10. ;
              format HC06_MOE_VC71 $10. ;
              format HC01_EST_VC74 $3. ;
              format HC01_MOE_VC74 $3. ;
              format HC02_EST_VC74 $10. ;
              format HC02_MOE_VC74 $10. ;
              format HC03_EST_VC74 $3. ;
              format HC03_MOE_VC74 $3. ;
              format HC04_EST_VC74 $10. ;
              format HC04_MOE_VC74 $10. ;
              format HC05_EST_VC74 $3. ;
              format HC05_MOE_VC74 $3. ;
              format HC06_EST_VC74 $10. ;
              format HC06_MOE_VC74 $10. ;
              format HC01_EST_VC75 $3. ;
              format HC01_MOE_VC75 $3. ;
              format HC02_EST_VC75 $10. ;
              format HC02_MOE_VC75 $10. ;
              format HC03_EST_VC75 $3. ;
              format HC03_MOE_VC75 $3. ;
              format HC04_EST_VC75 $10. ;
              format HC04_MOE_VC75 $10. ;
              format HC05_EST_VC75 $3. ;
              format HC05_MOE_VC75 $3. ;
              format HC06_EST_VC75 $10. ;
              format HC06_MOE_VC75 $10. ;
              format HC01_EST_VC76 $3. ;
              format HC01_MOE_VC76 $3. ;
              format HC02_EST_VC76 $10. ;
              format HC02_MOE_VC76 $10. ;
              format HC03_EST_VC76 $3. ;
              format HC03_MOE_VC76 $3. ;
              format HC04_EST_VC76 $10. ;
              format HC04_MOE_VC76 $10. ;
              format HC05_EST_VC76 $3. ;
              format HC05_MOE_VC76 $3. ;
              format HC06_EST_VC76 $10. ;
              format HC06_MOE_VC76 $10. ;
              format HC01_EST_VC77 $3. ;
              format HC01_MOE_VC77 $3. ;
              format HC02_EST_VC77 $10. ;
              format HC02_MOE_VC77 $10. ;
              format HC03_EST_VC77 $3. ;
              format HC03_MOE_VC77 $3. ;
              format HC04_EST_VC77 $10. ;
              format HC04_MOE_VC77 $10. ;
              format HC05_EST_VC77 $3. ;
              format HC05_MOE_VC77 $3. ;
              format HC06_EST_VC77 $10. ;
              format HC06_MOE_VC77 $10. ;
              format HC01_EST_VC80 $10. ;
              format HC01_MOE_VC80 $10. ;
              format HC02_EST_VC80 $3. ;
              format HC02_MOE_VC80 $3. ;
              format HC03_EST_VC80 $10. ;
              format HC03_MOE_VC80 $10. ;
              format HC04_EST_VC80 $3. ;
              format HC04_MOE_VC80 $3. ;
              format HC05_EST_VC80 $10. ;
              format HC05_MOE_VC80 $10. ;
              format HC06_EST_VC80 $3. ;
              format HC06_MOE_VC80 $3. ;
              format HC01_EST_VC81 $5. ;
              format HC01_MOE_VC81 $4. ;
              format HC02_EST_VC81 $3. ;
              format HC02_MOE_VC81 $3. ;
              format HC03_EST_VC81 $5. ;
              format HC03_MOE_VC81 $5. ;
              format HC04_EST_VC81 $3. ;
              format HC04_MOE_VC81 $3. ;
              format HC05_EST_VC81 $5. ;
              format HC05_MOE_VC81 $5. ;
              format HC06_EST_VC81 $3. ;
              format HC06_MOE_VC81 $3. ;
              format HC01_EST_VC82 $10. ;
              format HC01_MOE_VC82 $10. ;
              format HC02_EST_VC82 $3. ;
              format HC02_MOE_VC82 $3. ;
              format HC03_EST_VC82 $5. ;
              format HC03_MOE_VC82 $4. ;
              format HC04_EST_VC82 $3. ;
              format HC04_MOE_VC82 $3. ;
              format HC05_EST_VC82 $5. ;
              format HC05_MOE_VC82 $5. ;
              format HC06_EST_VC82 $3. ;
              format HC06_MOE_VC82 $3. ;
							format HC01_EST_VC83 $10. ;
              format HC01_MOE_VC83 $10. ;
              format HC02_EST_VC83 $3. ;
              format HC02_MOE_VC83 $3. ;
              format HC03_EST_VC83 $5. ;
              format HC03_MOE_VC83 $5. ;
              format HC04_EST_VC83 $3. ;
              format HC04_MOE_VC83 $3. ;
              format HC05_EST_VC83 $5. ;
              format HC05_MOE_VC83 $4. ;
              format HC06_EST_VC83 $3. ;
              format HC06_MOE_VC83 $3. ;
              format HC01_EST_VC84 $10. ;
              format HC01_MOE_VC84 $10. ;
              format HC02_EST_VC84 $3. ;
              format HC02_MOE_VC84 $3. ;
              format HC03_EST_VC84 $5. ;
              format HC03_MOE_VC84 $5. ;
              format HC04_EST_VC84 $3. ;
              format HC04_MOE_VC84 $3. ;
              format HC05_EST_VC84 $10. ;
              format HC05_MOE_VC84 $10. ;
              format HC06_EST_VC84 $3. ;
              format HC06_MOE_VC84 $3. ;
              format HC01_EST_VC85 $5. ;
              format HC01_MOE_VC85 $5. ;
              format HC02_EST_VC85 $3. ;
              format HC02_MOE_VC85 $3. ;
              format HC03_EST_VC85 $5. ;
              format HC03_MOE_VC85 $5. ;
              format HC04_EST_VC85 $3. ;
              format HC04_MOE_VC85 $3. ;
              format HC05_EST_VC85 $5. ;
              format HC05_MOE_VC85 $5. ;
              format HC06_EST_VC85 $3. ;
              format HC06_MOE_VC85 $3. ;
           input
                       GEO_id $
                       GEO_id2 $
                       GEO_display_label $
                       HC01_EST_VC02 $
                       HC01_MOE_VC02 $
                       HC02_EST_VC02 $
                       HC02_MOE_VC02 $
                       HC03_EST_VC02 $
                       HC03_MOE_VC02 $
                       HC04_EST_VC02 $
                       HC04_MOE_VC02 $
                       HC05_EST_VC02 $
                       HC05_MOE_VC02 $
                       HC06_EST_VC02 $
                       HC06_MOE_VC02 $
                       HC01_EST_VC03 $
                       HC01_MOE_VC03 $
                       HC02_EST_VC03 $
                       HC02_MOE_VC03 $
                       HC03_EST_VC03 $
                       HC03_MOE_VC03 $
                       HC04_EST_VC03 $
                       HC04_MOE_VC03 $
                       HC05_EST_VC03 $
                       HC05_MOE_VC03 $
                       HC06_EST_VC03 $
                       HC06_MOE_VC03 $
                       HC01_EST_VC04 $
                       HC01_MOE_VC04 $
                       HC02_EST_VC04 $
                       HC02_MOE_VC04 $
                       HC03_EST_VC04 $
                       HC03_MOE_VC04 $
                       HC04_EST_VC04 $
                       HC04_MOE_VC04 $
                       HC05_EST_VC04 $
                       HC05_MOE_VC04 $
                       HC06_EST_VC04 $
                       HC06_MOE_VC04 $
                       HC01_EST_VC05 $
                       HC01_MOE_VC05 $
                       HC02_EST_VC05 $
                       HC02_MOE_VC05 $
                       HC03_EST_VC05 $
                       HC03_MOE_VC05 $
                       HC04_EST_VC05 $
                       HC04_MOE_VC05 $
                       HC05_EST_VC05 $
                       HC05_MOE_VC05 $
                       HC06_EST_VC05 $
                       HC06_MOE_VC05 $
                       HC01_EST_VC06 $
                       HC01_MOE_VC06 $
                       HC02_EST_VC06 $
                       HC02_MOE_VC06 $
                       HC03_EST_VC06 $
                       HC03_MOE_VC06 $
                       HC04_EST_VC06 $
                       HC04_MOE_VC06 $
                       HC05_EST_VC06 $
                       HC05_MOE_VC06 $
                       HC06_EST_VC06 $
                       HC06_MOE_VC06 $
                       HC01_EST_VC08 $
                       HC01_MOE_VC08 $
                       HC02_EST_VC08 $
                       HC02_MOE_VC08 $
                       HC03_EST_VC08 $
                       HC03_MOE_VC08 $
                       HC04_EST_VC08 $
                       HC04_MOE_VC08 $
                       HC05_EST_VC08 $
                       HC05_MOE_VC08 $
                       HC06_EST_VC08 $
                       HC06_MOE_VC08 $
                       HC01_EST_VC09 $
                       HC01_MOE_VC09 $
                       HC02_EST_VC09 $
                       HC02_MOE_VC09 $
                       HC03_EST_VC09 $
                       HC03_MOE_VC09 $
                       HC04_EST_VC09 $
                       HC04_MOE_VC09 $
                       HC05_EST_VC09 $
                       HC05_MOE_VC09 $
                       HC06_EST_VC09 $
                       HC06_MOE_VC09 $
                       HC01_EST_VC10 $
                       HC01_MOE_VC10 $
                       HC02_EST_VC10 $
                       HC02_MOE_VC10 $
                       HC03_EST_VC10 $
                       HC03_MOE_VC10 $
                       HC04_EST_VC10 $
                       HC04_MOE_VC10 $
                       HC05_EST_VC10 $
                       HC05_MOE_VC10 $
                       HC06_EST_VC10 $
                       HC06_MOE_VC10 $
                       HC01_EST_VC11 $
                       HC01_MOE_VC11 $
                       HC02_EST_VC11 $
                       HC02_MOE_VC11 $
                       HC03_EST_VC11 $
                       HC03_MOE_VC11 $
                       HC04_EST_VC11 $
                       HC04_MOE_VC11 $
                       HC05_EST_VC11 $
                       HC05_MOE_VC11 $
                       HC06_EST_VC11 $
                       HC06_MOE_VC11 $
                       HC01_EST_VC12 $
                       HC01_MOE_VC12 $
                       HC02_EST_VC12 $
                       HC02_MOE_VC12 $
                       HC03_EST_VC12 $
                       HC03_MOE_VC12 $
                       HC04_EST_VC12 $
                       HC04_MOE_VC12 $
                       HC05_EST_VC12 $
                       HC05_MOE_VC12 $
                       HC06_EST_VC12 $
                       HC06_MOE_VC12 $
                       HC01_EST_VC13 $
                       HC01_MOE_VC13 $
                       HC02_EST_VC13 $
                       HC02_MOE_VC13 $
                       HC03_EST_VC13 $
                       HC03_MOE_VC13 $
                       HC04_EST_VC13 $
                       HC04_MOE_VC13 $
                       HC05_EST_VC13 $
                       HC05_MOE_VC13 $
                       HC06_EST_VC13 $
                       HC06_MOE_VC13 $
                       HC01_EST_VC14 $
                       HC01_MOE_VC14 $
                       HC02_EST_VC14 $
                       HC02_MOE_VC14 $
                       HC03_EST_VC14 $
                       HC03_MOE_VC14 $
                       HC04_EST_VC14 $
                       HC04_MOE_VC14 $
                       HC05_EST_VC14 $
                       HC05_MOE_VC14 $
                       HC06_EST_VC14 $
                       HC06_MOE_VC14 $
                       HC01_EST_VC15 $
                       HC01_MOE_VC15 $
                       HC02_EST_VC15 $
                       HC02_MOE_VC15 $
                       HC03_EST_VC15 $
                       HC03_MOE_VC15 $
                       HC04_EST_VC15 $
                       HC04_MOE_VC15 $
                       HC05_EST_VC15 $
                       HC05_MOE_VC15 $
                       HC06_EST_VC15 $
                       HC06_MOE_VC15 $
                       HC01_EST_VC17 $
                       HC01_MOE_VC17 $
											 HC02_EST_VC17 $
                       HC02_MOE_VC17 $
                       HC03_EST_VC17 $
                       HC03_MOE_VC17 $
                       HC04_EST_VC17 $
                       HC04_MOE_VC17 $
                       HC05_EST_VC17 $
                       HC05_MOE_VC17 $
                       HC06_EST_VC17 $
                       HC06_MOE_VC17 $
                       HC01_EST_VC18 $
                       HC01_MOE_VC18 $
                       HC02_EST_VC18 $
                       HC02_MOE_VC18 $
                       HC03_EST_VC18 $
                       HC03_MOE_VC18 $
                       HC04_EST_VC18 $
                       HC04_MOE_VC18 $
                       HC05_EST_VC18 $
                       HC05_MOE_VC18 $
                       HC06_EST_VC18 $
                       HC06_MOE_VC18 $
                       HC01_EST_VC20 $
                       HC01_MOE_VC20 $
                       HC02_EST_VC20 $
                       HC02_MOE_VC20 $
                       HC03_EST_VC20 $
                       HC03_MOE_VC20 $
                       HC04_EST_VC20 $
                       HC04_MOE_VC20 $
                       HC05_EST_VC20 $
                       HC05_MOE_VC20 $
                       HC06_EST_VC20 $
                       HC06_MOE_VC20 $
                       HC01_EST_VC21 $
                       HC01_MOE_VC21 $
                       HC02_EST_VC21 $
                       HC02_MOE_VC21 $
                       HC03_EST_VC21 $
                       HC03_MOE_VC21 $
                       HC04_EST_VC21 $
                       HC04_MOE_VC21 $
                       HC05_EST_VC21 $
                       HC05_MOE_VC21 $
                       HC06_EST_VC21 $
                       HC06_MOE_VC21 $
                       HC01_EST_VC22 $
                       HC01_MOE_VC22 $
                       HC02_EST_VC22 $
                       HC02_MOE_VC22 $
                       HC03_EST_VC22 $
                       HC03_MOE_VC22 $
                       HC04_EST_VC22 $
                       HC04_MOE_VC22 $
                       HC05_EST_VC22 $
                       HC05_MOE_VC22 $
                       HC06_EST_VC22 $
                       HC06_MOE_VC22 $
                       HC01_EST_VC24 $
                       HC01_MOE_VC24 $
                       HC02_EST_VC24 $
                       HC02_MOE_VC24 $
                       HC03_EST_VC24 $
                       HC03_MOE_VC24 $
                       HC04_EST_VC24 $
                       HC04_MOE_VC24 $
                       HC05_EST_VC24 $
                       HC05_MOE_VC24 $
                       HC06_EST_VC24 $
                       HC06_MOE_VC24 $
                       HC01_EST_VC25 $
                       HC01_MOE_VC25 $
                       HC02_EST_VC25 $
                       HC02_MOE_VC25 $
                       HC03_EST_VC25 $
                       HC03_MOE_VC25 $
                       HC04_EST_VC25 $
                       HC04_MOE_VC25 $
                       HC05_EST_VC25 $
                       HC05_MOE_VC25 $
                       HC06_EST_VC25 $
                       HC06_MOE_VC25 $
                       HC01_EST_VC26 $
                       HC01_MOE_VC26 $
                       HC02_EST_VC26 $
                       HC02_MOE_VC26 $
                       HC03_EST_VC26 $
                       HC03_MOE_VC26 $
                       HC04_EST_VC26 $
                       HC04_MOE_VC26 $
                       HC05_EST_VC26 $
                       HC05_MOE_VC26 $
                       HC06_EST_VC26 $
                       HC06_MOE_VC26 $
                       HC01_EST_VC28 $
                       HC01_MOE_VC28 $
                       HC02_EST_VC28 $
                       HC02_MOE_VC28 $
                       HC03_EST_VC28 $
                       HC03_MOE_VC28 $
                       HC04_EST_VC28 $
                       HC04_MOE_VC28 $
                       HC05_EST_VC28 $
                       HC05_MOE_VC28 $
                       HC06_EST_VC28 $
                       HC06_MOE_VC28 $
                       HC01_EST_VC29 $
                       HC01_MOE_VC29 $
                       HC02_EST_VC29 $
                       HC02_MOE_VC29 $
                       HC03_EST_VC29 $
                       HC03_MOE_VC29 $
                       HC04_EST_VC29 $
                       HC04_MOE_VC29 $
                       HC05_EST_VC29 $
                       HC05_MOE_VC29 $
                       HC06_EST_VC29 $
                       HC06_MOE_VC29 $
                       HC01_EST_VC30 $
                       HC01_MOE_VC30 $
                       HC02_EST_VC30 $
                       HC02_MOE_VC30 $
                       HC03_EST_VC30 $
                       HC03_MOE_VC30 $
                       HC04_EST_VC30 $
                       HC04_MOE_VC30 $
                       HC05_EST_VC30 $
                       HC05_MOE_VC30 $
                       HC06_EST_VC30 $
                       HC06_MOE_VC30 $
                       HC01_EST_VC32 $
                       HC01_MOE_VC32 $
                       HC02_EST_VC32 $
                       HC02_MOE_VC32 $
                       HC03_EST_VC32 $
                       HC03_MOE_VC32 $
                       HC04_EST_VC32 $
                       HC04_MOE_VC32 $
                       HC05_EST_VC32 $
                       HC05_MOE_VC32 $
                       HC06_EST_VC32 $
                       HC06_MOE_VC32 $
                       HC01_EST_VC33 $
                       HC01_MOE_VC33 $
                       HC02_EST_VC33 $
                       HC02_MOE_VC33 $
                       HC03_EST_VC33 $
                       HC03_MOE_VC33 $
                       HC04_EST_VC33 $
                       HC04_MOE_VC33 $
                       HC05_EST_VC33 $
                       HC05_MOE_VC33 $
                       HC06_EST_VC33 $
                       HC06_MOE_VC33 $
                       HC01_EST_VC34 $
                       HC01_MOE_VC34 $
                       HC02_EST_VC34 $
                       HC02_MOE_VC34 $
                       HC03_EST_VC34 $
                       HC03_MOE_VC34 $
                       HC04_EST_VC34 $
                       HC04_MOE_VC34 $
                       HC05_EST_VC34 $
                       HC05_MOE_VC34 $
                       HC06_EST_VC34 $
                       HC06_MOE_VC34 $
                       HC01_EST_VC37 $
                       HC01_MOE_VC37 $
                       HC02_EST_VC37 $
                       HC02_MOE_VC37 $
                       HC03_EST_VC37 $
                       HC03_MOE_VC37 $
                       HC04_EST_VC37 $
                       HC04_MOE_VC37 $
                       HC05_EST_VC37 $
                       HC05_MOE_VC37 $
                       HC06_EST_VC37 $
                       HC06_MOE_VC37 $
                       HC01_EST_VC38 $
                       HC01_MOE_VC38 $
                       HC02_EST_VC38 $
                       HC02_MOE_VC38 $
                       HC03_EST_VC38 $
                       HC03_MOE_VC38 $
                       HC04_EST_VC38 $
                       HC04_MOE_VC38 $
                       HC05_EST_VC38 $
                       HC05_MOE_VC38 $
                       HC06_EST_VC38 $
                       HC06_MOE_VC38 $
                       HC01_EST_VC39 $
                       HC01_MOE_VC39 $
                       HC02_EST_VC39 $
                       HC02_MOE_VC39 $
                       HC03_EST_VC39 $
                       HC03_MOE_VC39 $
                       HC04_EST_VC39 $
                       HC04_MOE_VC39 $
											 HC05_EST_VC39 $
                       HC05_MOE_VC39 $
                       HC06_EST_VC39 $
                       HC06_MOE_VC39 $
                       HC01_EST_VC41 $
                       HC01_MOE_VC41 $
                       HC02_EST_VC41 $
                       HC02_MOE_VC41 $
                       HC03_EST_VC41 $
                       HC03_MOE_VC41 $
                       HC04_EST_VC41 $
                       HC04_MOE_VC41 $
                       HC05_EST_VC41 $
                       HC05_MOE_VC41 $
                       HC06_EST_VC41 $
                       HC06_MOE_VC41 $
                       HC01_EST_VC42 $
                       HC01_MOE_VC42 $
                       HC02_EST_VC42 $
                       HC02_MOE_VC42 $
                       HC03_EST_VC42 $
                       HC03_MOE_VC42 $
                       HC04_EST_VC42 $
                       HC04_MOE_VC42 $
                       HC05_EST_VC42 $
                       HC05_MOE_VC42 $
                       HC06_EST_VC42 $
                       HC06_MOE_VC42 $
                       HC01_EST_VC43 $
                       HC01_MOE_VC43 $
                       HC02_EST_VC43 $
                       HC02_MOE_VC43 $
                       HC03_EST_VC43 $
                       HC03_MOE_VC43 $
                       HC04_EST_VC43 $
                       HC04_MOE_VC43 $
                       HC05_EST_VC43 $
                       HC05_MOE_VC43 $
                       HC06_EST_VC43 $
                       HC06_MOE_VC43 $
                       HC01_EST_VC45 $
                       HC01_MOE_VC45 $
                       HC02_EST_VC45 $
                       HC02_MOE_VC45 $
                       HC03_EST_VC45 $
                       HC03_MOE_VC45 $
                       HC04_EST_VC45 $
                       HC04_MOE_VC45 $
                       HC05_EST_VC45 $
                       HC05_MOE_VC45 $
                       HC06_EST_VC45 $
                       HC06_MOE_VC45 $
                       HC01_EST_VC46 $
                       HC01_MOE_VC46 $
                       HC02_EST_VC46 $
                       HC02_MOE_VC46 $
                       HC03_EST_VC46 $
                       HC03_MOE_VC46 $
                       HC04_EST_VC46 $
                       HC04_MOE_VC46 $
                       HC05_EST_VC46 $
                       HC05_MOE_VC46 $
                       HC06_EST_VC46 $
                       HC06_MOE_VC46 $
                       HC01_EST_VC47 $
                       HC01_MOE_VC47 $
                       HC02_EST_VC47 $
                       HC02_MOE_VC47 $
                       HC03_EST_VC47 $
                       HC03_MOE_VC47 $
                       HC04_EST_VC47 $
                       HC04_MOE_VC47 $
                       HC05_EST_VC47 $
                       HC05_MOE_VC47 $
                       HC06_EST_VC47 $
                       HC06_MOE_VC47 $
                       HC01_EST_VC49 $
                       HC01_MOE_VC49 $
                       HC02_EST_VC49 $
                       HC02_MOE_VC49 $
                       HC03_EST_VC49 $
                       HC03_MOE_VC49 $
                       HC04_EST_VC49 $
                       HC04_MOE_VC49 $
                       HC05_EST_VC49 $
                       HC05_MOE_VC49 $
                       HC06_EST_VC49 $
                       HC06_MOE_VC49 $
                       HC01_EST_VC50 $
                       HC01_MOE_VC50 $
                       HC02_EST_VC50 $
                       HC02_MOE_VC50 $
                       HC03_EST_VC50 $
                       HC03_MOE_VC50 $
                       HC04_EST_VC50 $
                       HC04_MOE_VC50 $
                       HC05_EST_VC50 $
                       HC05_MOE_VC50 $
                       HC06_EST_VC50 $
                       HC06_MOE_VC50 $
                       HC01_EST_VC51 $
                       HC01_MOE_VC51 $
                       HC02_EST_VC51 $
                       HC02_MOE_VC51 $
                       HC03_EST_VC51 $
                       HC03_MOE_VC51 $
                       HC04_EST_VC51 $
                       HC04_MOE_VC51 $
                       HC05_EST_VC51 $
                       HC05_MOE_VC51 $
                       HC06_EST_VC51 $
                       HC06_MOE_VC51 $
                       HC01_EST_VC53 $
                       HC01_MOE_VC53 $
                       HC02_EST_VC53 $
                       HC02_MOE_VC53 $
                       HC03_EST_VC53 $
                       HC03_MOE_VC53 $
                       HC04_EST_VC53 $
                       HC04_MOE_VC53 $
                       HC05_EST_VC53 $
                       HC05_MOE_VC53 $
                       HC06_EST_VC53 $
                       HC06_MOE_VC53 $
                       HC01_EST_VC54 $
                       HC01_MOE_VC54 $
                       HC02_EST_VC54 $
                       HC02_MOE_VC54 $
                       HC03_EST_VC54 $
                       HC03_MOE_VC54 $
                       HC04_EST_VC54 $
                       HC04_MOE_VC54 $
                       HC05_EST_VC54 $
                       HC05_MOE_VC54 $
                       HC06_EST_VC54 $
                       HC06_MOE_VC54 $
                       HC01_EST_VC55 $
                       HC01_MOE_VC55 $
                       HC02_EST_VC55 $
                       HC02_MOE_VC55 $
                       HC03_EST_VC55 $
                       HC03_MOE_VC55 $
                       HC04_EST_VC55 $
                       HC04_MOE_VC55 $ 
                       HC05_EST_VC55 $
                       HC05_MOE_VC55 $
                       HC06_EST_VC55 $
                       HC06_MOE_VC55 $
                       HC01_EST_VC57 $
                       HC01_MOE_VC57 $
                       HC02_EST_VC57 $
                       HC02_MOE_VC57 $
                       HC03_EST_VC57 $
                       HC03_MOE_VC57 $
                       HC04_EST_VC57 $
                       HC04_MOE_VC57 $
                       HC05_EST_VC57 $
                       HC05_MOE_VC57 $
                       HC06_EST_VC57 $
                       HC06_MOE_VC57 $
                       HC01_EST_VC58 $
                       HC01_MOE_VC58 $
                       HC02_EST_VC58 $
                       HC02_MOE_VC58 $
                       HC03_EST_VC58 $
                       HC03_MOE_VC58 $
                       HC04_EST_VC58 $
                       HC04_MOE_VC58 $
                       HC05_EST_VC58 $
                       HC05_MOE_VC58 $
                       HC06_EST_VC58 $
                       HC06_MOE_VC58 $
                       HC01_EST_VC59 $
                       HC01_MOE_VC59 $
                       HC02_EST_VC59 $
                       HC02_MOE_VC59 $
                       HC03_EST_VC59 $
                       HC03_MOE_VC59 $
                       HC04_EST_VC59 $
                       HC04_MOE_VC59 $
                       HC05_EST_VC59 $
                       HC05_MOE_VC59 $
                       HC06_EST_VC59 $
                       HC06_MOE_VC59 $
                       HC01_EST_VC61 $
                       HC01_MOE_VC61 $
                       HC02_EST_VC61 $
                       HC02_MOE_VC61 $
                       HC03_EST_VC61 $
                       HC03_MOE_VC61 $
                       HC04_EST_VC61 $
                       HC04_MOE_VC61 $
                       HC05_EST_VC61 $
                       HC05_MOE_VC61 $
                       HC06_EST_VC61 $
                       HC06_MOE_VC61 $
                       HC01_EST_VC62 $
                       HC01_MOE_VC62 $
											 HC02_EST_VC62 $
                       HC02_MOE_VC62 $
                       HC03_EST_VC62 $
                       HC03_MOE_VC62 $
                       HC04_EST_VC62 $
                       HC04_MOE_VC62 $
                       HC05_EST_VC62 $
                       HC05_MOE_VC62 $
                       HC06_EST_VC62 $
                       HC06_MOE_VC62 $
                       HC01_EST_VC63 $
                       HC01_MOE_VC63 $
                       HC02_EST_VC63 $
                       HC02_MOE_VC63 $
                       HC03_EST_VC63 $
                       HC03_MOE_VC63 $
                       HC04_EST_VC63 $
                       HC04_MOE_VC63 $
                       HC05_EST_VC63 $
                       HC05_MOE_VC63 $
                       HC06_EST_VC63 $
                       HC06_MOE_VC63 $
                       HC01_EST_VC65 $
                       HC01_MOE_VC65 $
                       HC02_EST_VC65 $
                       HC02_MOE_VC65 $
                       HC03_EST_VC65 $
                       HC03_MOE_VC65 $
                       HC04_EST_VC65 $
                       HC04_MOE_VC65 $
                       HC05_EST_VC65 $
                       HC05_MOE_VC65 $
                       HC06_EST_VC65 $
                       HC06_MOE_VC65 $
                       HC01_EST_VC66 $
                       HC01_MOE_VC66 $
                       HC02_EST_VC66 $
                       HC02_MOE_VC66 $
                       HC03_EST_VC66 $
                       HC03_MOE_VC66 $
                       HC04_EST_VC66 $
                       HC04_MOE_VC66 $
                       HC05_EST_VC66 $
                       HC05_MOE_VC66 $
                       HC06_EST_VC66 $
                       HC06_MOE_VC66 $
                       HC01_EST_VC67 $
                       HC01_MOE_VC67 $
                       HC02_EST_VC67 $
                       HC02_MOE_VC67 $
                       HC03_EST_VC67 $
                       HC03_MOE_VC67 $
                       HC04_EST_VC67 $
                       HC04_MOE_VC67 $
                       HC05_EST_VC67 $
                       HC05_MOE_VC67 $
                       HC06_EST_VC67 $
                       HC06_MOE_VC67 $
                       HC01_EST_VC69 $
                       HC01_MOE_VC69 $
                       HC02_EST_VC69 $
                       HC02_MOE_VC69 $
                       HC03_EST_VC69 $
                       HC03_MOE_VC69 $
                       HC04_EST_VC69 $
                       HC04_MOE_VC69 $
                       HC05_EST_VC69 $
                       HC05_MOE_VC69 $
                       HC06_EST_VC69 $
                       HC06_MOE_VC69 $
                       HC01_EST_VC70 $
                       HC01_MOE_VC70 $
                       HC02_EST_VC70 $
                       HC02_MOE_VC70 $
                       HC03_EST_VC70 $
                       HC03_MOE_VC70 $
                       HC04_EST_VC70 $
                       HC04_MOE_VC70 $
                       HC05_EST_VC70 $
                       HC05_MOE_VC70 $
                       HC06_EST_VC70 $
                       HC06_MOE_VC70 $
                       HC01_EST_VC71 $
                       HC01_MOE_VC71 $
                       HC02_EST_VC71 $
                       HC02_MOE_VC71 $
                       HC03_EST_VC71 $
                       HC03_MOE_VC71 $
                       HC04_EST_VC71 $
                       HC04_MOE_VC71 $
                       HC05_EST_VC71 $
                       HC05_MOE_VC71 $
                       HC06_EST_VC71 $
                       HC06_MOE_VC71 $
                       HC01_EST_VC74 $
                       HC01_MOE_VC74 $
                       HC02_EST_VC74 $
                       HC02_MOE_VC74 $
                       HC03_EST_VC74 $
                       HC03_MOE_VC74 $
                       HC04_EST_VC74 $
                       HC04_MOE_VC74 $
                       HC05_EST_VC74 $
                       HC05_MOE_VC74 $
                       HC06_EST_VC74 $
                       HC06_MOE_VC74 $
                       HC01_EST_VC75 $
                       HC01_MOE_VC75 $
                       HC02_EST_VC75 $
                       HC02_MOE_VC75 $
                       HC03_EST_VC75 $
                       HC03_MOE_VC75 $
                       HC04_EST_VC75 $
                       HC04_MOE_VC75 $
                       HC05_EST_VC75 $
                       HC05_MOE_VC75 $
                       HC06_EST_VC75 $
                       HC06_MOE_VC75 $
                       HC01_EST_VC76 $
                       HC01_MOE_VC76 $
                       HC02_EST_VC76 $
                       HC02_MOE_VC76 $
                       HC03_EST_VC76 $
                       HC03_MOE_VC76 $
                       HC04_EST_VC76 $
                       HC04_MOE_VC76 $
                       HC05_EST_VC76 $
                       HC05_MOE_VC76 $
                       HC06_EST_VC76 $
                       HC06_MOE_VC76 $
                       HC01_EST_VC77 $
                       HC01_MOE_VC77 $
                       HC02_EST_VC77 $
                       HC02_MOE_VC77 $
                       HC03_EST_VC77 $
                       HC03_MOE_VC77 $
                       HC04_EST_VC77 $
                       HC04_MOE_VC77 $
                       HC05_EST_VC77 $
                       HC05_MOE_VC77 $
                       HC06_EST_VC77 $
                       HC06_MOE_VC77 $
                       HC01_EST_VC80 $
                       HC01_MOE_VC80 $
                       HC02_EST_VC80 $
                       HC02_MOE_VC80 $
                       HC03_EST_VC80 $
                       HC03_MOE_VC80 $
                       HC04_EST_VC80 $
                       HC04_MOE_VC80 $
                       HC05_EST_VC80 $
                       HC05_MOE_VC80 $
                       HC06_EST_VC80 $
                       HC06_MOE_VC80 $
                       HC01_EST_VC81 $
                       HC01_MOE_VC81 $
                       HC02_EST_VC81 $
                       HC02_MOE_VC81 $
                       HC03_EST_VC81 $
                       HC03_MOE_VC81 $
                       HC04_EST_VC81 $
                       HC04_MOE_VC81 $
                       HC05_EST_VC81 $
                       HC05_MOE_VC81 $
                       HC06_EST_VC81 $
                       HC06_MOE_VC81 $
                       HC01_EST_VC82 $
                       HC01_MOE_VC82 $
                       HC02_EST_VC82 $
                       HC02_MOE_VC82 $
                       HC03_EST_VC82 $
                       HC03_MOE_VC82 $
                       HC04_EST_VC82 $
                       HC04_MOE_VC82 $
                       HC05_EST_VC82 $
                       HC05_MOE_VC82 $
                       HC06_EST_VC82 $
                       HC06_MOE_VC82 $
                       HC01_EST_VC83 $
                       HC01_MOE_VC83 $
                       HC02_EST_VC83 $
                       HC02_MOE_VC83 $
                       HC03_EST_VC83 $
                       HC03_MOE_VC83 $
                       HC04_EST_VC83 $
                       HC04_MOE_VC83 $
                       HC05_EST_VC83 $
                       HC05_MOE_VC83 $
                       HC06_EST_VC83 $
                       HC06_MOE_VC83 $
                       HC01_EST_VC84 $
                       HC01_MOE_VC84 $
                       HC02_EST_VC84 $
                       HC02_MOE_VC84 $
                       HC03_EST_VC84 $
                       HC03_MOE_VC84 $
                       HC04_EST_VC84 $
                       HC04_MOE_VC84 $
                       HC05_EST_VC84 $
                       HC05_MOE_VC84 $
                       HC06_EST_VC84 $
                       HC06_MOE_VC84 $
                       HC01_EST_VC85 $
                       HC01_MOE_VC85 $
                       HC02_EST_VC85 $
                       HC02_MOE_VC85 $
                       HC03_EST_VC85 $
                       HC03_MOE_VC85 $
                       HC04_EST_VC85 $
                       HC04_MOE_VC85 $
                       HC05_EST_VC85 $
                       HC05_MOE_VC85 $
                       HC06_EST_VC85 $
                       HC06_MOE_VC85 $
           ;
           label
geo_id="Id - long geo"
geo_id2="Id2 - ZCTA5 no leading 0's"
GEO_display_label="ZCTA5 + 5 digit ZCTA"
HC01_EST_VC02="Total; Estimate; Population 18 to 24 years"
HC01_MOE_VC02="Total; Margin of Error; Population 18 to 24 years"
HC02_EST_VC02="Percent; Estimate; Population 18 to 24 years"
HC02_MOE_VC02="Percent; Margin of Error; Population 18 to 24 years"
HC03_EST_VC02="Male; Estimate; Population 18 to 24 years"
HC03_MOE_VC02="Male; Margin of Error; Population 18 to 24 years"
HC04_EST_VC02="Percent Male; Estimate; Population 18 to 24 years"
HC04_MOE_VC02="Percent Male; Margin of Error; Population 18 to 24 years"
HC05_EST_VC02="Female; Estimate; Population 18 to 24 years"
HC05_MOE_VC02="Female; Margin of Error; Population 18 to 24 years"
HC06_EST_VC02="Percent Female; Estimate; Population 18 to 24 years"
HC06_MOE_VC02="Percent Female; Margin of Error; Population 18 to 24 years"
HC01_EST_VC03="Total; Estimate; Population 18 to 24 years - Less than high school graduate"
HC01_MOE_VC03="Total; Margin of Error; Population 18 to 24 years - Less than high school graduate"
HC02_EST_VC03="Percent; Estimate; Population 18 to 24 years - Less than high school graduate"
HC02_MOE_VC03="Percent; Margin of Error; Population 18 to 24 years - Less than high school graduate"
HC03_EST_VC03="Male; Estimate; Population 18 to 24 years - Less than high school graduate"
HC03_MOE_VC03="Male; Margin of Error; Population 18 to 24 years - Less than high school graduate"
HC04_EST_VC03="Percent Male; Estimate; Population 18 to 24 years - Less than high school graduate"
HC04_MOE_VC03="Percent Male; Margin of Error; Population 18 to 24 years - Less than high school graduate"
HC05_EST_VC03="Female; Estimate; Population 18 to 24 years - Less than high school graduate"
HC05_MOE_VC03="Female; Margin of Error; Population 18 to 24 years - Less than high school graduate"
HC06_EST_VC03="Percent Female; Estimate; Population 18 to 24 years - Less than high school graduate"
HC06_MOE_VC03="Percent Female; Margin of Error; Population 18 to 24 years - Less than high school graduate"
HC01_EST_VC04="Total; Estimate; Population 18 to 24 years - High school graduate (includes equivalency)"
HC01_MOE_VC04="Total; Margin of Error; Population 18 to 24 years - High school graduate (includes equivalency)"
HC02_EST_VC04="Percent; Estimate; Population 18 to 24 years - High school graduate (includes equivalency)"
HC02_MOE_VC04="Percent; Margin of Error; Population 18 to 24 years - High school graduate (includes equivalency)"
HC03_EST_VC04="Male; Estimate; Population 18 to 24 years - High school graduate (includes equivalency)"
HC03_MOE_VC04="Male; Margin of Error; Population 18 to 24 years - High school graduate (includes equivalency)"
HC04_EST_VC04="Percent Male; Estimate; Population 18 to 24 years - High school graduate (includes equivalency)"
HC04_MOE_VC04="Percent Male; Margin of Error; Population 18 to 24 years - High school graduate (includes equivalency)"
HC05_EST_VC04="Female; Estimate; Population 18 to 24 years - High school graduate (includes equivalency)"
HC05_MOE_VC04="Female; Margin of Error; Population 18 to 24 years - High school graduate (includes equivalency)"
HC06_EST_VC04="Percent Female; Estimate; Population 18 to 24 years - High school graduate (includes equivalency)"
HC06_MOE_VC04="Percent Female; Margin of Error; Population 18 to 24 years - High school graduate (includes equivalency)"
HC01_EST_VC05="Total; Estimate; Population 18 to 24 years - Some college or associate's degree"
HC01_MOE_VC05="Total; Margin of Error; Population 18 to 24 years - Some college or associate's degree"
HC02_EST_VC05="Percent; Estimate; Population 18 to 24 years - Some college or associate's degree"
HC02_MOE_VC05="Percent; Margin of Error; Population 18 to 24 years - Some college or associate's degree"
HC03_EST_VC05="Male; Estimate; Population 18 to 24 years - Some college or associate's degree"
HC03_MOE_VC05="Male; Margin of Error; Population 18 to 24 years - Some college or associate's degree"
HC04_EST_VC05="Percent Male; Estimate; Population 18 to 24 years - Some college or associate's degree"
HC04_MOE_VC05="Percent Male; Margin of Error; Population 18 to 24 years - Some college or associate's degree"
HC05_EST_VC05="Female; Estimate; Population 18 to 24 years - Some college or associate's degree"
HC05_MOE_VC05="Female; Margin of Error; Population 18 to 24 years - Some college or associate's degree"
HC06_EST_VC05="Percent Female; Estimate; Population 18 to 24 years - Some college or associate's degree"
HC06_MOE_VC05="Percent Female; Margin of Error; Population 18 to 24 years - Some college or associate's degree"
HC01_EST_VC06="Total; Estimate; Population 18 to 24 years - bachelor's degree or higher"
HC01_MOE_VC06="Total; Margin of Error; Population 18 to 24 years - bachelor's degree or higher"
HC02_EST_VC06="Percent; Estimate; Population 18 to 24 years - bachelor's degree or higher"
HC02_MOE_VC06="Percent; Margin of Error; Population 18 to 24 years - bachelor's degree or higher"
HC03_EST_VC06="Male; Estimate; Population 18 to 24 years - bachelor's degree or higher"
HC03_MOE_VC06="Male; Margin of Error; Population 18 to 24 years - bachelor's degree or higher"
HC04_EST_VC06="Percent Male; Estimate; Population 18 to 24 years - bachelor's degree or higher"
HC04_MOE_VC06="Percent Male; Margin of Error; Population 18 to 24 years - bachelor's degree or higher"
HC05_EST_VC06="Female; Estimate; Population 18 to 24 years - bachelor's degree or higher"
HC05_MOE_VC06="Female; Margin of Error; Population 18 to 24 years - bachelor's degree or higher"
HC06_EST_VC06="Percent Female; Estimate; Population 18 to 24 years - bachelor's degree or higher"
HC06_MOE_VC06="Percent Female; Margin of Error; Population 18 to 24 years - bachelor's degree or higher"
HC01_EST_VC08="Total; Estimate; Population 25 years and over"
HC01_MOE_VC08="Total; Margin of Error; Population 25 years and over"
HC02_EST_VC08="Percent; Estimate; Population 25 years and over"
HC02_MOE_VC08="Percent; Margin of Error; Population 25 years and over"
HC03_EST_VC08="Male; Estimate; Population 25 years and over"
HC03_MOE_VC08="Male; Margin of Error; Population 25 years and over"
HC04_EST_VC08="Percent Male; Estimate; Population 25 years and over"
HC04_MOE_VC08="Percent Male; Margin of Error; Population 25 years and over"
HC05_EST_VC08="Female; Estimate; Population 25 years and over"
HC05_MOE_VC08="Female; Margin of Error; Population 25 years and over"
HC06_EST_VC08="Percent Female; Estimate; Population 25 years and over"
HC06_MOE_VC08="Percent Female; Margin of Error; Population 25 years and over"
HC01_EST_VC09="Total; Estimate; Population 25 years and over - Less than 9th grade"
HC01_MOE_VC09="Total; Margin of Error; Population 25 years and over - Less than 9th grade"
HC02_EST_VC09="Percent; Estimate; Population 25 years and over - Less than 9th grade"
HC02_MOE_VC09="Percent; Margin of Error; Population 25 years and over - Less than 9th grade"
HC03_EST_VC09="Male; Estimate; Population 25 years and over - Less than 9th grade"
HC03_MOE_VC09="Male; Margin of Error; Population 25 years and over - Less than 9th grade"
HC04_EST_VC09="Percent Male; Estimate; Population 25 years and over - Less than 9th grade"
HC04_MOE_VC09="Percent Male; Margin of Error; Population 25 years and over - Less than 9th grade"
HC05_EST_VC09="Female; Estimate; Population 25 years and over - Less than 9th grade"
HC05_MOE_VC09="Female; Margin of Error; Population 25 years and over - Less than 9th grade"
HC06_EST_VC09="Percent Female; Estimate; Population 25 years and over - Less than 9th grade"
HC06_MOE_VC09="Percent Female; Margin of Error; Population 25 years and over - Less than 9th grade"
HC01_EST_VC10="Total; Estimate; Population 25 years and over - 9th to 12th grade, no diploma"
HC01_MOE_VC10="Total; Margin of Error; Population 25 years and over - 9th to 12th grade, no diploma"
HC02_EST_VC10="Percent; Estimate; Population 25 years and over - 9th to 12th grade, no diploma"
HC02_MOE_VC10="Percent; Margin of Error; Population 25 years and over - 9th to 12th grade, no diploma"
HC03_EST_VC10="Male; Estimate; Population 25 years and over - 9th to 12th grade, no diploma"
HC03_MOE_VC10="Male; Margin of Error; Population 25 years and over - 9th to 12th grade, no diploma"
HC04_EST_VC10="Percent Male; Estimate; Population 25 years and over - 9th to 12th grade, no diploma"
HC04_MOE_VC10="Percent Male; Margin of Error; Population 25 years and over - 9th to 12th grade, no diploma"
HC05_EST_VC10="Female; Estimate; Population 25 years and over - 9th to 12th grade, no diploma"
HC05_MOE_VC10="Female; Margin of Error; Population 25 years and over - 9th to 12th grade, no diploma"
HC06_EST_VC10="Percent Female; Estimate; Population 25 years and over - 9th to 12th grade, no diploma"
HC06_MOE_VC10="Percent Female; Margin of Error; Population 25 years and over - 9th to 12th grade, no diploma"
HC01_EST_VC11="Total; Estimate; Population 25 years and over - High school graduate (includes equivalency)"
HC01_MOE_VC11="Total; Margin of Error; Population 25 years and over - High school graduate (includes equivalency)"
HC02_EST_VC11="Percent; Estimate; Population 25 years and over - High school graduate (includes equivalency)"
HC02_MOE_VC11="Percent; Margin of Error; Population 25 years and over - High school graduate (includes equivalency)"
HC03_EST_VC11="Male; Estimate; Population 25 years and over - High school graduate (includes equivalency)"
HC03_MOE_VC11="Male; Margin of Error; Population 25 years and over - High school graduate (includes equivalency)"
HC04_EST_VC11="Percent Male; Estimate; Population 25 years and over - High school graduate (includes equivalency)"
HC04_MOE_VC11="Percent Male; Margin of Error; Population 25 years and over - High school graduate (includes equivalency)"
HC05_EST_VC11="Female; Estimate; Population 25 years and over - High school graduate (includes equivalency)"
HC05_MOE_VC11="Female; Margin of Error; Population 25 years and over - High school graduate (includes equivalency)"
HC06_EST_VC11="Percent Female; Estimate; Population 25 years and over - High school graduate (includes equivalency)"
HC06_MOE_VC11="Percent Female; Margin of Error; Population 25 years and over - High school graduate (includes equivalency)"
HC01_EST_VC12="Total; Estimate; Population 25 years and over - Some college, no degree"
HC01_MOE_VC12="Total; Margin of Error; Population 25 years and over - Some college, no degree"
HC02_EST_VC12="Percent; Estimate; Population 25 years and over - Some college, no degree"
HC02_MOE_VC12="Percent; Margin of Error; Population 25 years and over - Some college, no degree"
HC03_EST_VC12="Male; Estimate; Population 25 years and over - Some college, no degree"
HC03_MOE_VC12="Male; Margin of Error; Population 25 years and over - Some college, no degree"
HC04_EST_VC12="Percent Male; Estimate; Population 25 years and over - Some college, no degree"
HC04_MOE_VC12="Percent Male; Margin of Error; Population 25 years and over - Some college, no degree"
HC05_EST_VC12="Female; Estimate; Population 25 years and over - Some college, no degree"
HC05_MOE_VC12="Female; Margin of Error; Population 25 years and over - Some college, no degree"
HC06_EST_VC12="Percent Female; Estimate; Population 25 years and over - Some college, no degree"
HC06_MOE_VC12="Percent Female; Margin of Error; Population 25 years and over - Some college, no degree"
HC01_EST_VC13="Total; Estimate; Population 25 years and over - associate's degree"
HC01_MOE_VC13="Total; Margin of Error; Population 25 years and over - associate's degree"
HC02_EST_VC13="Percent; Estimate; Population 25 years and over - associate's degree"
HC02_MOE_VC13="Percent; Margin of Error; Population 25 years and over - associate's degree"
HC03_EST_VC13="Male; Estimate; Population 25 years and over - associate's degree"
HC03_MOE_VC13="Male; Margin of Error; Population 25 years and over - associate's degree"
HC04_EST_VC13="Percent Male; Estimate; Population 25 years and over - associate's degree"
HC04_MOE_VC13="Percent Male; Margin of Error; Population 25 years and over - associate's degree"
HC05_EST_VC13="Female; Estimate; Population 25 years and over - associate's degree"
HC05_MOE_VC13="Female; Margin of Error; Population 25 years and over - associate's degree"
HC06_EST_VC13="Percent Female; Estimate; Population 25 years and over - associate's degree"
HC06_MOE_VC13="Percent Female; Margin of Error; Population 25 years and over - associate's degree"
HC01_EST_VC14="Total; Estimate; Population 25 years and over - bachelor's degree"
HC01_MOE_VC14="Total; Margin of Error; Population 25 years and over - bachelor's degree"
HC02_EST_VC14="Percent; Estimate; Population 25 years and over - bachelor's degree"
HC02_MOE_VC14="Percent; Margin of Error; Population 25 years and over - bachelor's degree"
HC03_EST_VC14="Male; Estimate; Population 25 years and over - bachelor's degree"
HC03_MOE_VC14="Male; Margin of Error; Population 25 years and over - bachelor's degree"
HC04_EST_VC14="Percent Male; Estimate; Population 25 years and over - bachelor's degree"
HC04_MOE_VC14="Percent Male; Margin of Error; Population 25 years and over - bachelor's degree"
HC05_EST_VC14="Female; Estimate; Population 25 years and over - bachelor's degree"
HC05_MOE_VC14="Female; Margin of Error; Population 25 years and over - bachelor's degree"
HC06_EST_VC14="Percent Female; Estimate; Population 25 years and over - bachelor's degree"
HC06_MOE_VC14="Percent Female; Margin of Error; Population 25 years and over - bachelor's degree"
HC01_EST_VC15="Total; Estimate; Population 25 years and over - Graduate or professional degree"
HC01_MOE_VC15="Total; Margin of Error; Population 25 years and over - Graduate or professional degree"
HC02_EST_VC15="Percent; Estimate; Population 25 years and over - Graduate or professional degree"
HC02_MOE_VC15="Percent; Margin of Error; Population 25 years and over - Graduate or professional degree"
HC03_EST_VC15="Male; Estimate; Population 25 years and over - Graduate or professional degree"
HC03_MOE_VC15="Male; Margin of Error; Population 25 years and over - Graduate or professional degree"
HC04_EST_VC15="Percent Male; Estimate; Population 25 years and over - Graduate or professional degree"
HC04_MOE_VC15="Percent Male; Margin of Error; Population 25 years and over - Graduate or professional degree"
HC05_EST_VC15="Female; Estimate; Population 25 years and over - Graduate or professional degree"
HC05_MOE_VC15="Female; Margin of Error; Population 25 years and over - Graduate or professional degree"
HC06_EST_VC15="Percent Female; Estimate; Population 25 years and over - Graduate or professional degree"
HC06_MOE_VC15="Percent Female; Margin of Error; Population 25 years and over - Graduate or professional degree"
HC01_EST_VC17="Total; Estimate; Percent high school graduate or higher"
HC01_MOE_VC17="Total; Margin of Error; Percent high school graduate or higher"
HC02_EST_VC17="Percent; Estimate; Percent high school graduate or higher"
HC02_MOE_VC17="Percent; Margin of Error; Percent high school graduate or higher"
HC03_EST_VC17="Male; Estimate; Percent high school graduate or higher"
HC03_MOE_VC17="Male; Margin of Error; Percent high school graduate or higher"
HC04_EST_VC17="Percent Male; Estimate; Percent high school graduate or higher"
HC04_MOE_VC17="Percent Male; Margin of Error; Percent high school graduate or higher"
HC05_EST_VC17="Female; Estimate; Percent high school graduate or higher"
HC05_MOE_VC17="Female; Margin of Error; Percent high school graduate or higher"
HC06_EST_VC17="Percent Female; Estimate; Percent high school graduate or higher"
HC06_MOE_VC17="Percent Female; Margin of Error; Percent high school graduate or higher"
HC01_EST_VC18="Total; Estimate; Percent bachelor's degree or higher"
HC01_MOE_VC18="Total; Margin of Error; Percent bachelor's degree or higher"
HC02_EST_VC18="Percent; Estimate; Percent bachelor's degree or higher"
HC02_MOE_VC18="Percent; Margin of Error; Percent bachelor's degree or higher"
HC03_EST_VC18="Male; Estimate; Percent bachelor's degree or higher"
HC03_MOE_VC18="Male; Margin of Error; Percent bachelor's degree or higher"
HC04_EST_VC18="Percent Male; Estimate; Percent bachelor's degree or higher"
HC04_MOE_VC18="Percent Male; Margin of Error; Percent bachelor's degree or higher"
HC05_EST_VC18="Female; Estimate; Percent bachelor's degree or higher"
HC05_MOE_VC18="Female; Margin of Error; Percent bachelor's degree or higher"
HC06_EST_VC18="Percent Female; Estimate; Percent bachelor's degree or higher"
HC06_MOE_VC18="Percent Female; Margin of Error; Percent bachelor's degree or higher"
HC01_EST_VC20="Total; Estimate; Population 25 to 34 years"
HC01_MOE_VC20="Total; Margin of Error; Population 25 to 34 years"
HC02_EST_VC20="Percent; Estimate; Population 25 to 34 years"
HC02_MOE_VC20="Percent; Margin of Error; Population 25 to 34 years"
HC03_EST_VC20="Male; Estimate; Population 25 to 34 years"
HC03_MOE_VC20="Male; Margin of Error; Population 25 to 34 years"
HC04_EST_VC20="Percent Male; Estimate; Population 25 to 34 years"
HC04_MOE_VC20="Percent Male; Margin of Error; Population 25 to 34 years"
HC05_EST_VC20="Female; Estimate; Population 25 to 34 years"
HC05_MOE_VC20="Female; Margin of Error; Population 25 to 34 years"
HC06_EST_VC20="Percent Female; Estimate; Population 25 to 34 years"
HC06_MOE_VC20="Percent Female; Margin of Error; Population 25 to 34 years"
HC01_EST_VC21="Total; Estimate; Population 25 to 34 years - High school graduate or higher"
HC01_MOE_VC21="Total; Margin of Error; Population 25 to 34 years - High school graduate or higher"
HC02_EST_VC21="Percent; Estimate; Population 25 to 34 years - High school graduate or higher"
HC02_MOE_VC21="Percent; Margin of Error; Population 25 to 34 years - High school graduate or higher"
HC03_EST_VC21="Male; Estimate; Population 25 to 34 years - High school graduate or higher"
HC03_MOE_VC21="Male; Margin of Error; Population 25 to 34 years - High school graduate or higher"
HC04_EST_VC21="Percent Male; Estimate; Population 25 to 34 years - High school graduate or higher"
HC04_MOE_VC21="Percent Male; Margin of Error; Population 25 to 34 years - High school graduate or higher"
HC05_EST_VC21="Female; Estimate; Population 25 to 34 years - High school graduate or higher"
HC05_MOE_VC21="Female; Margin of Error; Population 25 to 34 years - High school graduate or higher"
HC06_EST_VC21="Percent Female; Estimate; Population 25 to 34 years - High school graduate or higher"
HC06_MOE_VC21="Percent Female; Margin of Error; Population 25 to 34 years - High school graduate or higher"
HC01_EST_VC22="Total; Estimate; Population 25 to 34 years - bachelor's degree or higher"
HC01_MOE_VC22="Total; Margin of Error; Population 25 to 34 years - bachelor's degree or higher"
HC02_EST_VC22="Percent; Estimate; Population 25 to 34 years - bachelor's degree or higher"
HC02_MOE_VC22="Percent; Margin of Error; Population 25 to 34 years - bachelor's degree or higher"
HC03_EST_VC22="Male; Estimate; Population 25 to 34 years - bachelor's degree or higher"
HC03_MOE_VC22="Male; Margin of Error; Population 25 to 34 years - bachelor's degree or higher"
HC04_EST_VC22="Percent Male; Estimate; Population 25 to 34 years - bachelor's degree or higher"
HC04_MOE_VC22="Percent Male; Margin of Error; Population 25 to 34 years - bachelor's degree or higher"
HC05_EST_VC22="Female; Estimate; Population 25 to 34 years - bachelor's degree or higher"
HC05_MOE_VC22="Female; Margin of Error; Population 25 to 34 years - bachelor's degree or higher"
HC06_EST_VC22="Percent Female; Estimate; Population 25 to 34 years - bachelor's degree or higher"
HC06_MOE_VC22="Percent Female; Margin of Error; Population 25 to 34 years - bachelor's degree or higher"
HC01_EST_VC24="Total; Estimate; Population 35 to 44 years"
HC01_MOE_VC24="Total; Margin of Error; Population 35 to 44 years"
HC02_EST_VC24="Percent; Estimate; Population 35 to 44 years"
HC02_MOE_VC24="Percent; Margin of Error; Population 35 to 44 years"
HC03_EST_VC24="Male; Estimate; Population 35 to 44 years"
HC03_MOE_VC24="Male; Margin of Error; Population 35 to 44 years"
HC04_EST_VC24="Percent Male; Estimate; Population 35 to 44 years"
HC04_MOE_VC24="Percent Male; Margin of Error; Population 35 to 44 years"
HC05_EST_VC24="Female; Estimate; Population 35 to 44 years"
HC05_MOE_VC24="Female; Margin of Error; Population 35 to 44 years"
HC06_EST_VC24="Percent Female; Estimate; Population 35 to 44 years"
HC06_MOE_VC24="Percent Female; Margin of Error; Population 35 to 44 years"
HC01_EST_VC25="Total; Estimate; Population 35 to 44 years - High school graduate or higher"
HC01_MOE_VC25="Total; Margin of Error; Population 35 to 44 years - High school graduate or higher"
HC02_EST_VC25="Percent; Estimate; Population 35 to 44 years - High school graduate or higher"
HC02_MOE_VC25="Percent; Margin of Error; Population 35 to 44 years - High school graduate or higher"
HC03_EST_VC25="Male; Estimate; Population 35 to 44 years - High school graduate or higher"
HC03_MOE_VC25="Male; Margin of Error; Population 35 to 44 years - High school graduate or higher"
HC04_EST_VC25="Percent Male; Estimate; Population 35 to 44 years - High school graduate or higher"
HC04_MOE_VC25="Percent Male; Margin of Error; Population 35 to 44 years - High school graduate or higher"
HC05_EST_VC25="Female; Estimate; Population 35 to 44 years - High school graduate or higher"
HC05_MOE_VC25="Female; Margin of Error; Population 35 to 44 years - High school graduate or higher"
HC06_EST_VC25="Percent Female; Estimate; Population 35 to 44 years - High school graduate or higher"
HC06_MOE_VC25="Percent Female; Margin of Error; Population 35 to 44 years - High school graduate or higher"
HC01_EST_VC26="Total; Estimate; Population 35 to 44 years - bachelor's degree or higher"
HC01_MOE_VC26="Total; Margin of Error; Population 35 to 44 years - bachelor's degree or higher"
HC02_EST_VC26="Percent; Estimate; Population 35 to 44 years - bachelor's degree or higher"
HC02_MOE_VC26="Percent; Margin of Error; Population 35 to 44 years - bachelor's degree or higher"
HC03_EST_VC26="Male; Estimate; Population 35 to 44 years - bachelor's degree or higher"
HC03_MOE_VC26="Male; Margin of Error; Population 35 to 44 years - bachelor's degree or higher"
HC04_EST_VC26="Percent Male; Estimate; Population 35 to 44 years - bachelor's degree or higher"
HC04_MOE_VC26="Percent Male; Margin of Error; Population 35 to 44 years - bachelor's degree or higher"
HC05_EST_VC26="Female; Estimate; Population 35 to 44 years - bachelor's degree or higher"
HC05_MOE_VC26="Female; Margin of Error; Population 35 to 44 years - bachelor's degree or higher"
HC06_EST_VC26="Percent Female; Estimate; Population 35 to 44 years - bachelor's degree or higher"
HC06_MOE_VC26="Percent Female; Margin of Error; Population 35 to 44 years - bachelor's degree or higher"
HC01_EST_VC28="Total; Estimate; Population 45 to 64 years"
HC01_MOE_VC28="Total; Margin of Error; Population 45 to 64 years"
HC02_EST_VC28="Percent; Estimate; Population 45 to 64 years"
HC02_MOE_VC28="Percent; Margin of Error; Population 45 to 64 years"
HC03_EST_VC28="Male; Estimate; Population 45 to 64 years"
HC03_MOE_VC28="Male; Margin of Error; Population 45 to 64 years"
HC04_EST_VC28="Percent Male; Estimate; Population 45 to 64 years"
HC04_MOE_VC28="Percent Male; Margin of Error; Population 45 to 64 years"
HC05_EST_VC28="Female; Estimate; Population 45 to 64 years"
HC05_MOE_VC28="Female; Margin of Error; Population 45 to 64 years"
HC06_EST_VC28="Percent Female; Estimate; Population 45 to 64 years"
HC06_MOE_VC28="Percent Female; Margin of Error; Population 45 to 64 years"
HC01_EST_VC29="Total; Estimate; Population 45 to 64 years - High school graduate or higher"
HC01_MOE_VC29="Total; Margin of Error; Population 45 to 64 years - High school graduate or higher"
HC02_EST_VC29="Percent; Estimate; Population 45 to 64 years - High school graduate or higher"
HC02_MOE_VC29="Percent; Margin of Error; Population 45 to 64 years - High school graduate or higher"
HC03_EST_VC29="Male; Estimate; Population 45 to 64 years - High school graduate or higher"
HC03_MOE_VC29="Male; Margin of Error; Population 45 to 64 years - High school graduate or higher"
HC04_EST_VC29="Percent Male; Estimate; Population 45 to 64 years - High school graduate or higher"
HC04_MOE_VC29="Percent Male; Margin of Error; Population 45 to 64 years - High school graduate or higher"
HC05_EST_VC29="Female; Estimate; Population 45 to 64 years - High school graduate or higher"
HC05_MOE_VC29="Female; Margin of Error; Population 45 to 64 years - High school graduate or higher"
HC06_EST_VC29="Percent Female; Estimate; Population 45 to 64 years - High school graduate or higher"
HC06_MOE_VC29="Percent Female; Margin of Error; Population 45 to 64 years - High school graduate or higher"
HC01_EST_VC30="Total; Estimate; Population 45 to 64 years - bachelor's degree or higher"
HC01_MOE_VC30="Total; Margin of Error; Population 45 to 64 years - bachelor's degree or higher"
HC02_EST_VC30="Percent; Estimate; Population 45 to 64 years - bachelor's degree or higher"
HC02_MOE_VC30="Percent; Margin of Error; Population 45 to 64 years - bachelor's degree or higher"
HC03_EST_VC30="Male; Estimate; Population 45 to 64 years - bachelor's degree or higher"
HC03_MOE_VC30="Male; Margin of Error; Population 45 to 64 years - bachelor's degree or higher"
HC04_EST_VC30="Percent Male; Estimate; Population 45 to 64 years - bachelor's degree or higher"
HC04_MOE_VC30="Percent Male; Margin of Error; Population 45 to 64 years - bachelor's degree or higher"
HC05_EST_VC30="Female; Estimate; Population 45 to 64 years - bachelor's degree or higher"
HC05_MOE_VC30="Female; Margin of Error; Population 45 to 64 years - bachelor's degree or higher"
HC06_EST_VC30="Percent Female; Estimate; Population 45 to 64 years - bachelor's degree or higher"
HC06_MOE_VC30="Percent Female; Margin of Error; Population 45 to 64 years - bachelor's degree or higher"
HC01_EST_VC32="Total; Estimate; Population 65 years and over"
HC01_MOE_VC32="Total; Margin of Error; Population 65 years and over"
HC02_EST_VC32="Percent; Estimate; Population 65 years and over"
HC02_MOE_VC32="Percent; Margin of Error; Population 65 years and over"
HC03_EST_VC32="Male; Estimate; Population 65 years and over"
HC03_MOE_VC32="Male; Margin of Error; Population 65 years and over"
HC04_EST_VC32="Percent Male; Estimate; Population 65 years and over"
HC04_MOE_VC32="Percent Male; Margin of Error; Population 65 years and over"
HC05_EST_VC32="Female; Estimate; Population 65 years and over"
HC05_MOE_VC32="Female; Margin of Error; Population 65 years and over"
HC06_EST_VC32="Percent Female; Estimate; Population 65 years and over"
HC06_MOE_VC32="Percent Female; Margin of Error; Population 65 years and over"
HC01_EST_VC33="Total; Estimate; Population 65 years and over - High school graduate or higher"
HC01_MOE_VC33="Total; Margin of Error; Population 65 years and over - High school graduate or higher"
HC02_EST_VC33="Percent; Estimate; Population 65 years and over - High school graduate or higher"
HC02_MOE_VC33="Percent; Margin of Error; Population 65 years and over - High school graduate or higher"
HC03_EST_VC33="Male; Estimate; Population 65 years and over - High school graduate or higher"
HC03_MOE_VC33="Male; Margin of Error; Population 65 years and over - High school graduate or higher"
HC04_EST_VC33="Percent Male; Estimate; Population 65 years and over - High school graduate or higher"
HC04_MOE_VC33="Percent Male; Margin of Error; Population 65 years and over - High school graduate or higher"
HC05_EST_VC33="Female; Estimate; Population 65 years and over - High school graduate or higher"
HC05_MOE_VC33="Female; Margin of Error; Population 65 years and over - High school graduate or higher"
HC06_EST_VC33="Percent Female; Estimate; Population 65 years and over - High school graduate or higher"
HC06_MOE_VC33="Percent Female; Margin of Error; Population 65 years and over - High school graduate or higher"
HC01_EST_VC34="Total; Estimate; Population 65 years and over - bachelor's degree or higher"
HC01_MOE_VC34="Total; Margin of Error; Population 65 years and over - bachelor's degree or higher"
HC02_EST_VC34="Percent; Estimate; Population 65 years and over - bachelor's degree or higher"
HC02_MOE_VC34="Percent; Margin of Error; Population 65 years and over - bachelor's degree or higher"
HC03_EST_VC34="Male; Estimate; Population 65 years and over - bachelor's degree or higher"
HC03_MOE_VC34="Male; Margin of Error; Population 65 years and over - bachelor's degree or higher"
HC04_EST_VC34="Percent Male; Estimate; Population 65 years and over - bachelor's degree or higher"
HC04_MOE_VC34="Percent Male; Margin of Error; Population 65 years and over - bachelor's degree or higher"
HC05_EST_VC34="Female; Estimate; Population 65 years and over - bachelor's degree or higher"
HC05_MOE_VC34="Female; Margin of Error; Population 65 years and over - bachelor's degree or higher"
HC06_EST_VC34="Percent Female; Estimate; Population 65 years and over - bachelor's degree or higher"
HC06_MOE_VC34="Percent Female; Margin of Error; Population 65 years and over - bachelor's degree or higher"
HC01_EST_VC37="Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone"
HC01_MOE_VC37="Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone"
HC02_EST_VC37="Percent; Estimate; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone"
HC02_MOE_VC37="Percent; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone"
HC03_EST_VC37="Male; Estimate; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone"
HC03_MOE_VC37="Male; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone"
HC04_EST_VC37="Percent Male; Estimate; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone"
HC04_MOE_VC37="Percent Male; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone"
HC05_EST_VC37="Female; Estimate; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone"
HC05_MOE_VC37="Female; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone"
HC06_EST_VC37="Percent Female; Estimate; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone"
HC06_MOE_VC37="Percent Female; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone"
HC01_EST_VC38="Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - High school graduate or higher"
HC01_MOE_VC38="Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - High school graduate or higher"
HC02_EST_VC38="Percent; Estimate; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - High school graduate or higher"
HC02_MOE_VC38="Percent; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - High school graduate or higher"
HC03_EST_VC38="Male; Estimate; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - High school graduate or higher"
HC03_MOE_VC38="Male; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - High school graduate or higher"
HC04_EST_VC38="Percent Male; Estimate; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - High school graduate or higher"
HC04_MOE_VC38="Percent Male; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - High school graduate or higher"
HC05_EST_VC38="Female; Estimate; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - High school graduate or higher"
HC05_MOE_VC38="Female; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - High school graduate or higher"
HC06_EST_VC38="Percent Female; Estimate; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - High school graduate or higher"
HC06_MOE_VC38="Percent Female; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - High school graduate or higher"
HC01_EST_VC39="Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - bachelor's degree or higher"
HC01_MOE_VC39="Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - bachelor's degree or higher"
HC02_EST_VC39="Percent; Estimate; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - bachelor's degree or higher"
HC02_MOE_VC39="Percent; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - bachelor's degree or higher"
HC03_EST_VC39="Male; Estimate; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - bachelor's degree or higher"
HC03_MOE_VC39="Male; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - bachelor's degree or higher"
HC04_EST_VC39="Percent Male; Estimate; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - bachelor's degree or higher"
HC04_MOE_VC39="Percent Male; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - bachelor's degree or higher"
HC05_EST_VC39="Female; Estimate; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - bachelor's degree or higher"
HC05_MOE_VC39="Female; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - bachelor's degree or higher"
HC06_EST_VC39="Percent Female; Estimate; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - bachelor's degree or higher"
HC06_MOE_VC39="Percent Female; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT - White alone - bachelor's degree or higher"
HC01_EST_VC41="Total; Estimate; White alone, not Hispanic or Latino"
HC01_MOE_VC41="Total; Margin of Error; White alone, not Hispanic or Latino"
HC02_EST_VC41="Percent; Estimate; White alone, not Hispanic or Latino"
HC02_MOE_VC41="Percent; Margin of Error; White alone, not Hispanic or Latino"
HC03_EST_VC41="Male; Estimate; White alone, not Hispanic or Latino"
HC03_MOE_VC41="Male; Margin of Error; White alone, not Hispanic or Latino"
HC04_EST_VC41="Percent Male; Estimate; White alone, not Hispanic or Latino"
HC04_MOE_VC41="Percent Male; Margin of Error; White alone, not Hispanic or Latino"
HC05_EST_VC41="Female; Estimate; White alone, not Hispanic or Latino"
HC05_MOE_VC41="Female; Margin of Error; White alone, not Hispanic or Latino"
HC06_EST_VC41="Percent Female; Estimate; White alone, not Hispanic or Latino"
HC06_MOE_VC41="Percent Female; Margin of Error; White alone, not Hispanic or Latino"
HC01_EST_VC42="Total; Estimate; White alone, not Hispanic or Latino - High school graduate or higher"
HC01_MOE_VC42="Total; Margin of Error; White alone, not Hispanic or Latino - High school graduate or higher"
HC02_EST_VC42="Percent; Estimate; White alone, not Hispanic or Latino - High school graduate or higher"
HC02_MOE_VC42="Percent; Margin of Error; White alone, not Hispanic or Latino - High school graduate or higher"
HC03_EST_VC42="Male; Estimate; White alone, not Hispanic or Latino - High school graduate or higher"
HC03_MOE_VC42="Male; Margin of Error; White alone, not Hispanic or Latino - High school graduate or higher"
HC04_EST_VC42="Percent Male; Estimate; White alone, not Hispanic or Latino - High school graduate or higher"
HC04_MOE_VC42="Percent Male; Margin of Error; White alone, not Hispanic or Latino - High school graduate or higher"
HC05_EST_VC42="Female; Estimate; White alone, not Hispanic or Latino - High school graduate or higher"
HC05_MOE_VC42="Female; Margin of Error; White alone, not Hispanic or Latino - High school graduate or higher"
HC06_EST_VC42="Percent Female; Estimate; White alone, not Hispanic or Latino - High school graduate or higher"
HC06_MOE_VC42="Percent Female; Margin of Error; White alone, not Hispanic or Latino - High school graduate or higher"
HC01_EST_VC43="Total; Estimate; White alone, not Hispanic or Latino - bachelor's degree or higher"
HC01_MOE_VC43="Total; Margin of Error; White alone, not Hispanic or Latino - bachelor's degree or higher"
HC02_EST_VC43="Percent; Estimate; White alone, not Hispanic or Latino - bachelor's degree or higher"
HC02_MOE_VC43="Percent; Margin of Error; White alone, not Hispanic or Latino - bachelor's degree or higher"
HC03_EST_VC43="Male; Estimate; White alone, not Hispanic or Latino - bachelor's degree or higher"
HC03_MOE_VC43="Male; Margin of Error; White alone, not Hispanic or Latino - bachelor's degree or higher"
HC04_EST_VC43="Percent Male; Estimate; White alone, not Hispanic or Latino - bachelor's degree or higher"
HC04_MOE_VC43="Percent Male; Margin of Error; White alone, not Hispanic or Latino - bachelor's degree or higher"
HC05_EST_VC43="Female; Estimate; White alone, not Hispanic or Latino - bachelor's degree or higher"
HC05_MOE_VC43="Female; Margin of Error; White alone, not Hispanic or Latino - bachelor's degree or higher"
HC06_EST_VC43="Percent Female; Estimate; White alone, not Hispanic or Latino - bachelor's degree or higher"
HC06_MOE_VC43="Percent Female; Margin of Error; White alone, not Hispanic or Latino - bachelor's degree or higher"
HC01_EST_VC45="Total; Estimate; Black alone"
HC01_MOE_VC45="Total; Margin of Error; Black alone"
HC02_EST_VC45="Percent; Estimate; Black alone"
HC02_MOE_VC45="Percent; Margin of Error; Black alone"
HC03_EST_VC45="Male; Estimate; Black alone"
HC03_MOE_VC45="Male; Margin of Error; Black alone"
HC04_EST_VC45="Percent Male; Estimate; Black alone"
HC04_MOE_VC45="Percent Male; Margin of Error; Black alone"
HC05_EST_VC45="Female; Estimate; Black alone"
HC05_MOE_VC45="Female; Margin of Error; Black alone"
HC06_EST_VC45="Percent Female; Estimate; Black alone"
HC06_MOE_VC45="Percent Female; Margin of Error; Black alone"
HC01_EST_VC46="Total; Estimate; Black alone - High school graduate or higher"
HC01_MOE_VC46="Total; Margin of Error; Black alone - High school graduate or higher"
HC02_EST_VC46="Percent; Estimate; Black alone - High school graduate or higher"
HC02_MOE_VC46="Percent; Margin of Error; Black alone - High school graduate or higher"
HC03_EST_VC46="Male; Estimate; Black alone - High school graduate or higher"
HC03_MOE_VC46="Male; Margin of Error; Black alone - High school graduate or higher"
HC04_EST_VC46="Percent Male; Estimate; Black alone - High school graduate or higher"
HC04_MOE_VC46="Percent Male; Margin of Error; Black alone - High school graduate or higher"
HC05_EST_VC46="Female; Estimate; Black alone - High school graduate or higher"
HC05_MOE_VC46="Female; Margin of Error; Black alone - High school graduate or higher"
HC06_EST_VC46="Percent Female; Estimate; Black alone - High school graduate or higher"
HC06_MOE_VC46="Percent Female; Margin of Error; Black alone - High school graduate or higher"
HC01_EST_VC47="Total; Estimate; Black alone - bachelor's degree or higher"
HC01_MOE_VC47="Total; Margin of Error; Black alone - bachelor's degree or higher"
HC02_EST_VC47="Percent; Estimate; Black alone - bachelor's degree or higher"
HC02_MOE_VC47="Percent; Margin of Error; Black alone - bachelor's degree or higher"
HC03_EST_VC47="Male; Estimate; Black alone - bachelor's degree or higher"
HC03_MOE_VC47="Male; Margin of Error; Black alone - bachelor's degree or higher"
HC04_EST_VC47="Percent Male; Estimate; Black alone - bachelor's degree or higher"
HC04_MOE_VC47="Percent Male; Margin of Error; Black alone - bachelor's degree or higher"
HC05_EST_VC47="Female; Estimate; Black alone - bachelor's degree or higher"
HC05_MOE_VC47="Female; Margin of Error; Black alone - bachelor's degree or higher"
HC06_EST_VC47="Percent Female; Estimate; Black alone - bachelor's degree or higher"
HC06_MOE_VC47="Percent Female; Margin of Error; Black alone - bachelor's degree or higher"
HC01_EST_VC49="Total; Estimate; American Indian or Alaska Native alone"
HC01_MOE_VC49="Total; Margin of Error; American Indian or Alaska Native alone"
HC02_EST_VC49="Percent; Estimate; American Indian or Alaska Native alone"
HC02_MOE_VC49="Percent; Margin of Error; American Indian or Alaska Native alone"
HC03_EST_VC49="Male; Estimate; American Indian or Alaska Native alone"
HC03_MOE_VC49="Male; Margin of Error; American Indian or Alaska Native alone"
HC04_EST_VC49="Percent Male; Estimate; American Indian or Alaska Native alone"
HC04_MOE_VC49="Percent Male; Margin of Error; American Indian or Alaska Native alone"
HC05_EST_VC49="Female; Estimate; American Indian or Alaska Native alone"
HC05_MOE_VC49="Female; Margin of Error; American Indian or Alaska Native alone"
HC06_EST_VC49="Percent Female; Estimate; American Indian or Alaska Native alone"
HC06_MOE_VC49="Percent Female; Margin of Error; American Indian or Alaska Native alone"
HC01_EST_VC50="Total; Estimate; American Indian or Alaska Native alone - High school graduate or higher"
HC01_MOE_VC50="Total; Margin of Error; American Indian or Alaska Native alone - High school graduate or higher"
HC02_EST_VC50="Percent; Estimate; American Indian or Alaska Native alone - High school graduate or higher"
HC02_MOE_VC50="Percent; Margin of Error; American Indian or Alaska Native alone - High school graduate or higher"
HC03_EST_VC50="Male; Estimate; American Indian or Alaska Native alone - High school graduate or higher"
HC03_MOE_VC50="Male; Margin of Error; American Indian or Alaska Native alone - High school graduate or higher"
HC04_EST_VC50="Percent Male; Estimate; American Indian or Alaska Native alone - High school graduate or higher"
HC04_MOE_VC50="Percent Male; Margin of Error; American Indian or Alaska Native alone - High school graduate or higher"
HC05_EST_VC50="Female; Estimate; American Indian or Alaska Native alone - High school graduate or higher"
HC05_MOE_VC50="Female; Margin of Error; American Indian or Alaska Native alone - High school graduate or higher"
HC06_EST_VC50="Percent Female; Estimate; American Indian or Alaska Native alone - High school graduate or higher"
HC06_MOE_VC50="Percent Female; Margin of Error; American Indian or Alaska Native alone - High school graduate or higher"
HC01_EST_VC51="Total; Estimate; American Indian or Alaska Native alone - bachelor's degree or higher"
HC01_MOE_VC51="Total; Margin of Error; American Indian or Alaska Native alone - bachelor's degree or higher"
HC02_EST_VC51="Percent; Estimate; American Indian or Alaska Native alone - bachelor's degree or higher"
HC02_MOE_VC51="Percent; Margin of Error; American Indian or Alaska Native alone - bachelor's degree or higher"
HC03_EST_VC51="Male; Estimate; American Indian or Alaska Native alone - bachelor's degree or higher"
HC03_MOE_VC51="Male; Margin of Error; American Indian or Alaska Native alone - bachelor's degree or higher"
HC04_EST_VC51="Percent Male; Estimate; American Indian or Alaska Native alone - bachelor's degree or higher"
HC04_MOE_VC51="Percent Male; Margin of Error; American Indian or Alaska Native alone - bachelor's degree or higher"
HC05_EST_VC51="Female; Estimate; American Indian or Alaska Native alone - bachelor's degree or higher"
HC05_MOE_VC51="Female; Margin of Error; American Indian or Alaska Native alone - bachelor's degree or higher"
HC06_EST_VC51="Percent Female; Estimate; American Indian or Alaska Native alone - bachelor's degree or higher"
HC06_MOE_VC51="Percent Female; Margin of Error; American Indian or Alaska Native alone - bachelor's degree or higher"
HC01_EST_VC53="Total; Estimate; Asian alone"
HC01_MOE_VC53="Total; Margin of Error; Asian alone"
HC02_EST_VC53="Percent; Estimate; Asian alone"
HC02_MOE_VC53="Percent; Margin of Error; Asian alone"
HC03_EST_VC53="Male; Estimate; Asian alone"
HC03_MOE_VC53="Male; Margin of Error; Asian alone"
HC04_EST_VC53="Percent Male; Estimate; Asian alone"
HC04_MOE_VC53="Percent Male; Margin of Error; Asian alone"
HC05_EST_VC53="Female; Estimate; Asian alone"
HC05_MOE_VC53="Female; Margin of Error; Asian alone"
HC06_EST_VC53="Percent Female; Estimate; Asian alone"
HC06_MOE_VC53="Percent Female; Margin of Error; Asian alone"
HC01_EST_VC54="Total; Estimate; Asian alone - High school graduate or higher"
HC01_MOE_VC54="Total; Margin of Error; Asian alone - High school graduate or higher"
HC02_EST_VC54="Percent; Estimate; Asian alone - High school graduate or higher"
HC02_MOE_VC54="Percent; Margin of Error; Asian alone - High school graduate or higher"
HC03_EST_VC54="Male; Estimate; Asian alone - High school graduate or higher"
HC03_MOE_VC54="Male; Margin of Error; Asian alone - High school graduate or higher"
HC04_EST_VC54="Percent Male; Estimate; Asian alone - High school graduate or higher"
HC04_MOE_VC54="Percent Male; Margin of Error; Asian alone - High school graduate or higher"
HC05_EST_VC54="Female; Estimate; Asian alone - High school graduate or higher"
HC05_MOE_VC54="Female; Margin of Error; Asian alone - High school graduate or higher"
HC06_EST_VC54="Percent Female; Estimate; Asian alone - High school graduate or higher"
HC06_MOE_VC54="Percent Female; Margin of Error; Asian alone - High school graduate or higher"
HC01_EST_VC55="Total; Estimate; Asian alone - bachelor's degree or higher"
HC01_MOE_VC55="Total; Margin of Error; Asian alone - bachelor's degree or higher"
HC02_EST_VC55="Percent; Estimate; Asian alone - bachelor's degree or higher"
HC02_MOE_VC55="Percent; Margin of Error; Asian alone - bachelor's degree or higher"
HC03_EST_VC55="Male; Estimate; Asian alone - bachelor's degree or higher"
HC03_MOE_VC55="Male; Margin of Error; Asian alone - bachelor's degree or higher"
HC04_EST_VC55="Percent Male; Estimate; Asian alone - bachelor's degree or higher"
HC04_MOE_VC55="Percent Male; Margin of Error; Asian alone - bachelor's degree or higher"
HC05_EST_VC55="Female; Estimate; Asian alone - bachelor's degree or higher"
HC05_MOE_VC55="Female; Margin of Error; Asian alone - bachelor's degree or higher"
HC06_EST_VC55="Percent Female; Estimate; Asian alone - bachelor's degree or higher"
HC06_MOE_VC55="Percent Female; Margin of Error; Asian alone - bachelor's degree or higher"
HC01_EST_VC57="Total; Estimate; Native Hawaiian and Other Pacific Islander alone"
HC01_MOE_VC57="Total; Margin of Error; Native Hawaiian and Other Pacific Islander alone"
HC02_EST_VC57="Percent; Estimate; Native Hawaiian and Other Pacific Islander alone"
HC02_MOE_VC57="Percent; Margin of Error; Native Hawaiian and Other Pacific Islander alone"
HC03_EST_VC57="Male; Estimate; Native Hawaiian and Other Pacific Islander alone"
HC03_MOE_VC57="Male; Margin of Error; Native Hawaiian and Other Pacific Islander alone"
HC04_EST_VC57="Percent Male; Estimate; Native Hawaiian and Other Pacific Islander alone"
HC04_MOE_VC57="Percent Male; Margin of Error; Native Hawaiian and Other Pacific Islander alone"
HC05_EST_VC57="Female; Estimate; Native Hawaiian and Other Pacific Islander alone"
HC05_MOE_VC57="Female; Margin of Error; Native Hawaiian and Other Pacific Islander alone"
HC06_EST_VC57="Percent Female; Estimate; Native Hawaiian and Other Pacific Islander alone"
HC06_MOE_VC57="Percent Female; Margin of Error; Native Hawaiian and Other Pacific Islander alone"
HC01_EST_VC58="Total; Estimate; Native Hawaiian and Other Pacific Islander alone - High school graduate or higher"
HC01_MOE_VC58="Total; Margin of Error; Native Hawaiian and Other Pacific Islander alone - High school graduate or higher"
HC02_EST_VC58="Percent; Estimate; Native Hawaiian and Other Pacific Islander alone - High school graduate or higher"
HC02_MOE_VC58="Percent; Margin of Error; Native Hawaiian and Other Pacific Islander alone - High school graduate or higher"
HC03_EST_VC58="Male; Estimate; Native Hawaiian and Other Pacific Islander alone - High school graduate or higher"
HC03_MOE_VC58="Male; Margin of Error; Native Hawaiian and Other Pacific Islander alone - High school graduate or higher"
HC04_EST_VC58="Percent Male; Estimate; Native Hawaiian and Other Pacific Islander alone - High school graduate or higher"
HC04_MOE_VC58="Percent Male; Margin of Error; Native Hawaiian and Other Pacific Islander alone - High school graduate or higher"
HC05_EST_VC58="Female; Estimate; Native Hawaiian and Other Pacific Islander alone - High school graduate or higher"
HC05_MOE_VC58="Female; Margin of Error; Native Hawaiian and Other Pacific Islander alone - High school graduate or higher"
HC06_EST_VC58="Percent Female; Estimate; Native Hawaiian and Other Pacific Islander alone - High school graduate or higher"
HC06_MOE_VC58="Percent Female; Margin of Error; Native Hawaiian and Other Pacific Islander alone - High school graduate or higher"
HC01_EST_VC59="Total; Estimate; Native Hawaiian and Other Pacific Islander alone - bachelor's degree or higher"
HC01_MOE_VC59="Total; Margin of Error; Native Hawaiian and Other Pacific Islander alone - bachelor's degree or higher"
HC02_EST_VC59="Percent; Estimate; Native Hawaiian and Other Pacific Islander alone - bachelor's degree or higher"
HC02_MOE_VC59="Percent; Margin of Error; Native Hawaiian and Other Pacific Islander alone - bachelor's degree or higher"
HC03_EST_VC59="Male; Estimate; Native Hawaiian and Other Pacific Islander alone - bachelor's degree or higher"
HC03_MOE_VC59="Male; Margin of Error; Native Hawaiian and Other Pacific Islander alone - bachelor's degree or higher"
HC04_EST_VC59="Percent Male; Estimate; Native Hawaiian and Other Pacific Islander alone - bachelor's degree or higher"
HC04_MOE_VC59="Percent Male; Margin of Error; Native Hawaiian and Other Pacific Islander alone - bachelor's degree or higher"
HC05_EST_VC59="Female; Estimate; Native Hawaiian and Other Pacific Islander alone - bachelor's degree or higher"
HC05_MOE_VC59="Female; Margin of Error; Native Hawaiian and Other Pacific Islander alone - bachelor's degree or higher"
HC06_EST_VC59="Percent Female; Estimate; Native Hawaiian and Other Pacific Islander alone - bachelor's degree or higher"
HC06_MOE_VC59="Percent Female; Margin of Error; Native Hawaiian and Other Pacific Islander alone - bachelor's degree or higher"
HC01_EST_VC61="Total; Estimate; Some other race alone"
HC01_MOE_VC61="Total; Margin of Error; Some other race alone"
HC02_EST_VC61="Percent; Estimate; Some other race alone"
HC02_MOE_VC61="Percent; Margin of Error; Some other race alone"
HC03_EST_VC61="Male; Estimate; Some other race alone"
HC03_MOE_VC61="Male; Margin of Error; Some other race alone"
HC04_EST_VC61="Percent Male; Estimate; Some other race alone"
HC04_MOE_VC61="Percent Male; Margin of Error; Some other race alone"
HC05_EST_VC61="Female; Estimate; Some other race alone"
HC05_MOE_VC61="Female; Margin of Error; Some other race alone"
HC06_EST_VC61="Percent Female; Estimate; Some other race alone"
HC06_MOE_VC61="Percent Female; Margin of Error; Some other race alone"
HC01_EST_VC62="Total; Estimate; Some other race alone - High school graduate or higher"
HC01_MOE_VC62="Total; Margin of Error; Some other race alone - High school graduate or higher"
HC02_EST_VC62="Percent; Estimate; Some other race alone - High school graduate or higher"
HC02_MOE_VC62="Percent; Margin of Error; Some other race alone - High school graduate or higher"
HC03_EST_VC62="Male; Estimate; Some other race alone - High school graduate or higher"
HC03_MOE_VC62="Male; Margin of Error; Some other race alone - High school graduate or higher"
HC04_EST_VC62="Percent Male; Estimate; Some other race alone - High school graduate or higher"
HC04_MOE_VC62="Percent Male; Margin of Error; Some other race alone - High school graduate or higher"
HC05_EST_VC62="Female; Estimate; Some other race alone - High school graduate or higher"
HC05_MOE_VC62="Female; Margin of Error; Some other race alone - High school graduate or higher"
HC06_EST_VC62="Percent Female; Estimate; Some other race alone - High school graduate or higher"
HC06_MOE_VC62="Percent Female; Margin of Error; Some other race alone - High school graduate or higher"
HC01_EST_VC63="Total; Estimate; Some other race alone - bachelor's degree or higher"
HC01_MOE_VC63="Total; Margin of Error; Some other race alone - bachelor's degree or higher"
HC02_EST_VC63="Percent; Estimate; Some other race alone - bachelor's degree or higher"
HC02_MOE_VC63="Percent; Margin of Error; Some other race alone - bachelor's degree or higher"
HC03_EST_VC63="Male; Estimate; Some other race alone - bachelor's degree or higher"
HC03_MOE_VC63="Male; Margin of Error; Some other race alone - bachelor's degree or higher"
HC04_EST_VC63="Percent Male; Estimate; Some other race alone - bachelor's degree or higher"
HC04_MOE_VC63="Percent Male; Margin of Error; Some other race alone - bachelor's degree or higher"
HC05_EST_VC63="Female; Estimate; Some other race alone - bachelor's degree or higher"
HC05_MOE_VC63="Female; Margin of Error; Some other race alone - bachelor's degree or higher"
HC06_EST_VC63="Percent Female; Estimate; Some other race alone - bachelor's degree or higher"
HC06_MOE_VC63="Percent Female; Margin of Error; Some other race alone - bachelor's degree or higher"
HC01_EST_VC65="Total; Estimate; Two or more races"
HC01_MOE_VC65="Total; Margin of Error; Two or more races"
HC02_EST_VC65="Percent; Estimate; Two or more races"
HC02_MOE_VC65="Percent; Margin of Error; Two or more races"
HC03_EST_VC65="Male; Estimate; Two or more races"
HC03_MOE_VC65="Male; Margin of Error; Two or more races"
HC04_EST_VC65="Percent Male; Estimate; Two or more races"
HC04_MOE_VC65="Percent Male; Margin of Error; Two or more races"
HC05_EST_VC65="Female; Estimate; Two or more races"
HC05_MOE_VC65="Female; Margin of Error; Two or more races"
HC06_EST_VC65="Percent Female; Estimate; Two or more races"
HC06_MOE_VC65="Percent Female; Margin of Error; Two or more races"
HC01_EST_VC66="Total; Estimate; Two or more races - High school graduate or higher"
HC01_MOE_VC66="Total; Margin of Error; Two or more races - High school graduate or higher"
HC02_EST_VC66="Percent; Estimate; Two or more races - High school graduate or higher"
HC02_MOE_VC66="Percent; Margin of Error; Two or more races - High school graduate or higher"
HC03_EST_VC66="Male; Estimate; Two or more races - High school graduate or higher"
HC03_MOE_VC66="Male; Margin of Error; Two or more races - High school graduate or higher"
HC04_EST_VC66="Percent Male; Estimate; Two or more races - High school graduate or higher"
HC04_MOE_VC66="Percent Male; Margin of Error; Two or more races - High school graduate or higher"
HC05_EST_VC66="Female; Estimate; Two or more races - High school graduate or higher"
HC05_MOE_VC66="Female; Margin of Error; Two or more races - High school graduate or higher"
HC06_EST_VC66="Percent Female; Estimate; Two or more races - High school graduate or higher"
HC06_MOE_VC66="Percent Female; Margin of Error; Two or more races - High school graduate or higher"
HC01_EST_VC67="Total; Estimate; Two or more races - bachelor's degree or higher"
HC01_MOE_VC67="Total; Margin of Error; Two or more races - bachelor's degree or higher"
HC02_EST_VC67="Percent; Estimate; Two or more races - bachelor's degree or higher"
HC02_MOE_VC67="Percent; Margin of Error; Two or more races - bachelor's degree or higher"
HC03_EST_VC67="Male; Estimate; Two or more races - bachelor's degree or higher"
HC03_MOE_VC67="Male; Margin of Error; Two or more races - bachelor's degree or higher"
HC04_EST_VC67="Percent Male; Estimate; Two or more races - bachelor's degree or higher"
HC04_MOE_VC67="Percent Male; Margin of Error; Two or more races - bachelor's degree or higher"
HC05_EST_VC67="Female; Estimate; Two or more races - bachelor's degree or higher"
HC05_MOE_VC67="Female; Margin of Error; Two or more races - bachelor's degree or higher"
HC06_EST_VC67="Percent Female; Estimate; Two or more races - bachelor's degree or higher"
HC06_MOE_VC67="Percent Female; Margin of Error; Two or more races - bachelor's degree or higher"
HC01_EST_VC69="Total; Estimate; Hispanic or Latino Origin"
HC01_MOE_VC69="Total; Margin of Error; Hispanic or Latino Origin"
HC02_EST_VC69="Percent; Estimate; Hispanic or Latino Origin"
HC02_MOE_VC69="Percent; Margin of Error; Hispanic or Latino Origin"
HC03_EST_VC69="Male; Estimate; Hispanic or Latino Origin"
HC03_MOE_VC69="Male; Margin of Error; Hispanic or Latino Origin"
HC04_EST_VC69="Percent Male; Estimate; Hispanic or Latino Origin"
HC04_MOE_VC69="Percent Male; Margin of Error; Hispanic or Latino Origin"
HC05_EST_VC69="Female; Estimate; Hispanic or Latino Origin"
HC05_MOE_VC69="Female; Margin of Error; Hispanic or Latino Origin"
HC06_EST_VC69="Percent Female; Estimate; Hispanic or Latino Origin"
HC06_MOE_VC69="Percent Female; Margin of Error; Hispanic or Latino Origin"
HC01_EST_VC70="Total; Estimate; Hispanic or Latino Origin - High school graduate or higher"
HC01_MOE_VC70="Total; Margin of Error; Hispanic or Latino Origin - High school graduate or higher"
HC02_EST_VC70="Percent; Estimate; Hispanic or Latino Origin - High school graduate or higher"
HC02_MOE_VC70="Percent; Margin of Error; Hispanic or Latino Origin - High school graduate or higher"
HC03_EST_VC70="Male; Estimate; Hispanic or Latino Origin - High school graduate or higher"
HC03_MOE_VC70="Male; Margin of Error; Hispanic or Latino Origin - High school graduate or higher"
HC04_EST_VC70="Percent Male; Estimate; Hispanic or Latino Origin - High school graduate or higher"
HC04_MOE_VC70="Percent Male; Margin of Error; Hispanic or Latino Origin - High school graduate or higher"
HC05_EST_VC70="Female; Estimate; Hispanic or Latino Origin - High school graduate or higher"
HC05_MOE_VC70="Female; Margin of Error; Hispanic or Latino Origin - High school graduate or higher"
HC06_EST_VC70="Percent Female; Estimate; Hispanic or Latino Origin - High school graduate or higher"
HC06_MOE_VC70="Percent Female; Margin of Error; Hispanic or Latino Origin - High school graduate or higher"
HC01_EST_VC71="Total; Estimate; Hispanic or Latino Origin - bachelor's degree or higher"
HC01_MOE_VC71="Total; Margin of Error; Hispanic or Latino Origin - bachelor's degree or higher"
HC02_EST_VC71="Percent; Estimate; Hispanic or Latino Origin - bachelor's degree or higher"
HC02_MOE_VC71="Percent; Margin of Error; Hispanic or Latino Origin - bachelor's degree or higher"
HC03_EST_VC71="Male; Estimate; Hispanic or Latino Origin - bachelor's degree or higher"
HC03_MOE_VC71="Male; Margin of Error; Hispanic or Latino Origin - bachelor's degree or higher"
HC04_EST_VC71="Percent Male; Estimate; Hispanic or Latino Origin - bachelor's degree or higher"
HC04_MOE_VC71="Percent Male; Margin of Error; Hispanic or Latino Origin - bachelor's degree or higher"
HC05_EST_VC71="Female; Estimate; Hispanic or Latino Origin - bachelor's degree or higher"
HC05_MOE_VC71="Female; Margin of Error; Hispanic or Latino Origin - bachelor's degree or higher"
HC06_EST_VC71="Percent Female; Estimate; Hispanic or Latino Origin - bachelor's degree or higher"
HC06_MOE_VC71="Percent Female; Margin of Error; Hispanic or Latino Origin - bachelor's degree or higher"
HC01_EST_VC74="Total; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Less than high school graduate"
HC01_MOE_VC74="Total; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Less than high school graduate"
HC02_EST_VC74="Percent; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Less than high school graduate"
HC02_MOE_VC74="Percent; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Less than high school graduate"
HC03_EST_VC74="Male; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Less than high school graduate"
HC03_MOE_VC74="Male; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Less than high school graduate"
HC04_EST_VC74="Percent Male; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Less than high school graduate"
HC04_MOE_VC74="Percent Male; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Less than high school graduate"
HC05_EST_VC74="Female; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Less than high school graduate"
HC05_MOE_VC74="Female; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Less than high school graduate"
HC06_EST_VC74="Percent Female; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Less than high school graduate"
HC06_MOE_VC74="Percent Female; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Less than high school graduate"
HC01_EST_VC75="Total; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - High school graduate (includes equivalency)"
HC01_MOE_VC75="Total; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - High school graduate (includes equivalency)"
HC02_EST_VC75="Percent; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - High school graduate (includes equivalency)"
HC02_MOE_VC75="Percent; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - High school graduate (includes equivalency)"
HC03_EST_VC75="Male; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - High school graduate (includes equivalency)"
HC03_MOE_VC75="Male; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - High school graduate (includes equivalency)"
HC04_EST_VC75="Percent Male; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - High school graduate (includes equivalency)"
HC04_MOE_VC75="Percent Male; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - High school graduate (includes equivalency)"
HC05_EST_VC75="Female; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - High school graduate (includes equivalency)"
HC05_MOE_VC75="Female; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - High school graduate (includes equivalency)"
HC06_EST_VC75="Percent Female; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - High school graduate (includes equivalency)"
HC06_MOE_VC75="Percent Female; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - High school graduate (includes equivalency)"
HC01_EST_VC76="Total; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Some college or associate's degree"
HC01_MOE_VC76="Total; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Some college or associate's degree"
HC02_EST_VC76="Percent; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Some college or associate's degree"
HC02_MOE_VC76="Percent; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Some college or associate's degree"
HC03_EST_VC76="Male; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Some college or associate's degree"
HC03_MOE_VC76="Male; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Some college or associate's degree"
HC04_EST_VC76="Percent Male; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Some college or associate's degree"
HC04_MOE_VC76="Percent Male; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Some college or associate's degree"
HC05_EST_VC76="Female; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Some college or associate's degree"
HC05_MOE_VC76="Female; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Some college or associate's degree"
HC06_EST_VC76="Percent Female; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Some college or associate's degree"
HC06_MOE_VC76="Percent Female; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - Some college or associate's degree"
HC01_EST_VC77="Total; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - bachelor's degree or higher"
HC01_MOE_VC77="Total; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - bachelor's degree or higher"
HC02_EST_VC77="Percent; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - bachelor's degree or higher"
HC02_MOE_VC77="Percent; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - bachelor's degree or higher"
HC03_EST_VC77="Male; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - bachelor's degree or higher"
HC03_MOE_VC77="Male; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - bachelor's degree or higher"
HC04_EST_VC77="Percent Male; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - bachelor's degree or higher"
HC04_MOE_VC77="Percent Male; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - bachelor's degree or higher"
HC05_EST_VC77="Female; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - bachelor's degree or higher"
HC05_MOE_VC77="Female; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - bachelor's degree or higher"
HC06_EST_VC77="Percent Female; Estimate; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - bachelor's degree or higher"
HC06_MOE_VC77="Percent Female; Margin of Error; POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL - bachelor's degree or higher"
HC01_EST_VC80="Total; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings"
HC01_MOE_VC80="Total; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings"
HC02_EST_VC80="Percent; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings"
HC02_MOE_VC80="Percent; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings"
HC03_EST_VC80="Male; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings"
HC03_MOE_VC80="Male; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings"
HC04_EST_VC80="Percent Male; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings"
HC04_MOE_VC80="Percent Male; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings"
HC05_EST_VC80="Female; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings"
HC05_MOE_VC80="Female; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings"
HC06_EST_VC80="Percent Female; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings"
HC06_MOE_VC80="Percent Female; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings"
HC01_EST_VC81="Total; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Less than high school graduate"
HC01_MOE_VC81="Total; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Less than high school graduate"
HC02_EST_VC81="Percent; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Less than high school graduate"
HC02_MOE_VC81="Percent; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Less than high school graduate"
HC03_EST_VC81="Male; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Less than high school graduate"
HC03_MOE_VC81="Male; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Less than high school graduate"
HC04_EST_VC81="Percent Male; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Less than high school graduate"
HC04_MOE_VC81="Percent Male; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Less than high school graduate"
HC05_EST_VC81="Female; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Less than high school graduate"
HC05_MOE_VC81="Female; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Less than high school graduate"
HC06_EST_VC81="Percent Female; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Less than high school graduate"
HC06_MOE_VC81="Percent Female; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Less than high school graduate"
HC01_EST_VC82="Total; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - High school graduate (includes equivalency)"
HC01_MOE_VC82="Total; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - High school graduate (includes equivalency)"
HC02_EST_VC82="Percent; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - High school graduate (includes equivalency)"
HC02_MOE_VC82="Percent; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - High school graduate (includes equivalency)"
HC03_EST_VC82="Male; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - High school graduate (includes equivalency)"
HC03_MOE_VC82="Male; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - High school graduate (includes equivalency)"
HC04_EST_VC82="Percent Male; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - High school graduate (includes equivalency)"
HC04_MOE_VC82="Percent Male; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - High school graduate (includes equivalency)"
HC05_EST_VC82="Female; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - High school graduate (includes equivalency)"
HC05_MOE_VC82="Female; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - High school graduate (includes equivalency)"
HC06_EST_VC82="Percent Female; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - High school graduate (includes equivalency)"
HC06_MOE_VC82="Percent Female; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - High school graduate (includes equivalency)"
HC01_EST_VC83="Total; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Some college or associate's degree"
HC01_MOE_VC83="Total; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Some college or associate's degree"
HC02_EST_VC83="Percent; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Some college or associate's degree"
HC02_MOE_VC83="Percent; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Some college or associate's degree"
HC03_EST_VC83="Male; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Some college or associate's degree"
HC03_MOE_VC83="Male; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Some college or associate's degree"
HC04_EST_VC83="Percent Male; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Some college or associate's degree"
HC04_MOE_VC83="Percent Male; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Some college or associate's degree"
HC05_EST_VC83="Female; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Some college or associate's degree"
HC05_MOE_VC83="Female; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Some college or associate's degree"
HC06_EST_VC83="Percent Female; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Some college or associate's degree"
HC06_MOE_VC83="Percent Female; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Some college or associate's degree"
HC01_EST_VC84="Total; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - bachelor's degree"
HC01_MOE_VC84="Total; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - bachelor's degree"
HC02_EST_VC84="Percent; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - bachelor's degree"
HC02_MOE_VC84="Percent; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - bachelor's degree"
HC03_EST_VC84="Male; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - bachelor's degree"
HC03_MOE_VC84="Male; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - bachelor's degree"
HC04_EST_VC84="Percent Male; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - bachelor's degree"
HC04_MOE_VC84="Percent Male; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - bachelor's degree"
HC05_EST_VC84="Female; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - bachelor's degree"
HC05_MOE_VC84="Female; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - bachelor's degree"
HC06_EST_VC84="Percent Female; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - bachelor's degree"
HC06_MOE_VC84="Percent Female; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - bachelor's degree"
HC01_EST_VC85="Total; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Graduate or professional degree"
HC01_MOE_VC85="Total; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Graduate or professional degree"
HC02_EST_VC85="Percent; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Graduate or professional degree"
HC02_MOE_VC85="Percent; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Graduate or professional degree"
HC03_EST_VC85="Male; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Graduate or professional degree"
HC03_MOE_VC85="Male; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Graduate or professional degree"
HC04_EST_VC85="Percent Male; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Graduate or professional degree"
HC04_MOE_VC85="Percent Male; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Graduate or professional degree"
HC05_EST_VC85="Female; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Graduate or professional degree"
HC05_MOE_VC85="Female; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Graduate or professional degree"
HC06_EST_VC85="Percent Female; Estimate; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Graduate or professional degree"
HC06_MOE_VC85="Percent Female; Margin of Error; MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Population 25 years and over with earnings - Graduate or professional degree"
;
           if _ERROR_ then call symputx("_EFIERR_",1);  /* set ERROR detection macro variable */
           run;
           
proc printto print="&&cont&yr./acs_s1501_&yr._raw.txt" new;
proc contents data=og&yr..acs_s1501_&yr._raw position; run;
proc printto; run;

%mend;